---
version: '3'

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - go build -o /dev/null main.go

  install:
    desc: Install the CLI binary
    cmds:
      - go install

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  coverage:
    desc: Run tests with coverage
    cmds:
      - go test --cover ./...

  coverage-html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  open-coverage-html:
    desc: Generate and open HTML coverage report
    deps:
      - coverage-html
    cmds:
      - open coverage.html

  pull-swagger:
    desc: Pull Jira API swagger definition
    preconditions:
      - sh: command -v curl
        msg: "curl is required but not installed"
    cmds:
      - curl -o swagger.json -sSL https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

  generate-swagger:
    desc: Generate Go client from swagger.json using openapi-generator
    preconditions:
      - sh: command -v openapi-generator
        msg: "openapi-generator is required but not installed. Install with: brew install openapi-generator"
      - sh: test -f swagger.json
        msg: "swagger.json not found. Run 'task pull-swagger' first"
    cmds:
      - rm -rf swagger
      - >-
        openapi-generator generate -i swagger.json -g go -o swagger --package-name swagger --additional-properties=isGoSubmodule=true --model-name-mappings Configuration=JiraConfiguration,NewUserDetails=JiraNewUserDetails --git-user-id alexhokl --git-repo-id jira-cli
      - task: fix-swagger-codegen-issues
      - go mod tidy

  fix-swagger-codegen-issues:
    desc: Fix code generation issues in swagger files
    internal: true
    preconditions:
      - sh: command -v perl
        msg: "perl is required but not installed"
      - sh: test -f swagger/model_field_metadata.go
        msg: "swagger/model_field_metadata.go not found. Run 'task generate-swagger' first"
      - sh: test -f swagger/model_field_create_metadata.go
        msg: "swagger/model_field_create_metadata.go not found. Run 'task generate-swagger' first"
      - sh: test -f swagger/model_mandatory_field_value.go
        msg: "swagger/model_mandatory_field_value.go not found. Run 'task generate-swagger' first"
    cmds:
      # Fix HasDefaultValue field/method name collision in model_field_metadata.go
      - perl -i -pe 's/HasDefaultValue \*bool/HasDefaultValueFlag *bool/g' swagger/model_field_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue\)/o.HasDefaultValueFlag)/g' swagger/model_field_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue,/o.HasDefaultValueFlag,/g' swagger/model_field_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue =/o.HasDefaultValueFlag =/g' swagger/model_field_metadata.go
      - perl -i -pe 's/= o\.HasDefaultValue$/= o.HasDefaultValueFlag/g' swagger/model_field_metadata.go
      - perl -i -pe 's/\*o\.HasDefaultValue$/*o.HasDefaultValueFlag/g' swagger/model_field_metadata.go
      # Fix HasDefaultValue field/method name collision in model_field_create_metadata.go
      - perl -i -pe 's/HasDefaultValue \*bool/HasDefaultValueFlag *bool/g' swagger/model_field_create_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue\)/o.HasDefaultValueFlag)/g' swagger/model_field_create_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue,/o.HasDefaultValueFlag,/g' swagger/model_field_create_metadata.go
      - perl -i -pe 's/o\.HasDefaultValue =/o.HasDefaultValueFlag =/g' swagger/model_field_create_metadata.go
      - perl -i -pe 's/= o\.HasDefaultValue$/= o.HasDefaultValueFlag/g' swagger/model_field_create_metadata.go
      - perl -i -pe 's/\*o\.HasDefaultValue$/*o.HasDefaultValueFlag/g' swagger/model_field_create_metadata.go
      # Fix undefined TYPE in model_mandatory_field_value.go
      - perl -i -pe 's/var type_ TYPE = "raw"/var type_ string = "raw"/g' swagger/model_mandatory_field_value.go
