/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// ScreenTabFieldsAPIService ScreenTabFieldsAPI service
type ScreenTabFieldsAPIService service

type ApiAddScreenTabFieldRequest struct {
	ctx context.Context
	ApiService *ScreenTabFieldsAPIService
	screenId int64
	tabId int64
	addFieldBean *AddFieldBean
}

func (r ApiAddScreenTabFieldRequest) AddFieldBean(addFieldBean AddFieldBean) ApiAddScreenTabFieldRequest {
	r.addFieldBean = &addFieldBean
	return r
}

func (r ApiAddScreenTabFieldRequest) Execute() (*ScreenableField, *http.Response, error) {
	return r.ApiService.AddScreenTabFieldExecute(r)
}

/*
AddScreenTabField Add screen tab field

Adds a field to a screen tab.

**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param screenId The ID of the screen.
 @param tabId The ID of the screen tab.
 @return ApiAddScreenTabFieldRequest
*/
func (a *ScreenTabFieldsAPIService) AddScreenTabField(ctx context.Context, screenId int64, tabId int64) ApiAddScreenTabFieldRequest {
	return ApiAddScreenTabFieldRequest{
		ApiService: a,
		ctx: ctx,
		screenId: screenId,
		tabId: tabId,
	}
}

// Execute executes the request
//  @return ScreenableField
func (a *ScreenTabFieldsAPIService) AddScreenTabFieldExecute(r ApiAddScreenTabFieldRequest) (*ScreenableField, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ScreenableField
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScreenTabFieldsAPIService.AddScreenTabField")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/rest/api/3/screens/{screenId}/tabs/{tabId}/fields"
	localVarPath = strings.Replace(localVarPath, "{"+"screenId"+"}", url.PathEscape(parameterValueToString(r.screenId, "screenId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tabId"+"}", url.PathEscape(parameterValueToString(r.tabId, "tabId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.addFieldBean == nil {
		return localVarReturnValue, nil, reportError("addFieldBean is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.addFieldBean
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetAllScreenTabFieldsRequest struct {
	ctx context.Context
	ApiService *ScreenTabFieldsAPIService
	screenId int64
	tabId int64
	projectKey *string
}

// The key of the project.
func (r ApiGetAllScreenTabFieldsRequest) ProjectKey(projectKey string) ApiGetAllScreenTabFieldsRequest {
	r.projectKey = &projectKey
	return r
}

func (r ApiGetAllScreenTabFieldsRequest) Execute() ([]ScreenableField, *http.Response, error) {
	return r.ApiService.GetAllScreenTabFieldsExecute(r)
}

/*
GetAllScreenTabFields Get all screen tab fields

Returns all fields for a screen tab.

**[Permissions](#permissions) required:**

 *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
 *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) when the project key is specified, providing that the screen is associated with the project through a Screen Scheme and Issue Type Screen Scheme.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param screenId The ID of the screen.
 @param tabId The ID of the screen tab.
 @return ApiGetAllScreenTabFieldsRequest
*/
func (a *ScreenTabFieldsAPIService) GetAllScreenTabFields(ctx context.Context, screenId int64, tabId int64) ApiGetAllScreenTabFieldsRequest {
	return ApiGetAllScreenTabFieldsRequest{
		ApiService: a,
		ctx: ctx,
		screenId: screenId,
		tabId: tabId,
	}
}

// Execute executes the request
//  @return []ScreenableField
func (a *ScreenTabFieldsAPIService) GetAllScreenTabFieldsExecute(r ApiGetAllScreenTabFieldsRequest) ([]ScreenableField, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []ScreenableField
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScreenTabFieldsAPIService.GetAllScreenTabFields")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/rest/api/3/screens/{screenId}/tabs/{tabId}/fields"
	localVarPath = strings.Replace(localVarPath, "{"+"screenId"+"}", url.PathEscape(parameterValueToString(r.screenId, "screenId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tabId"+"}", url.PathEscape(parameterValueToString(r.tabId, "tabId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.projectKey != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "projectKey", r.projectKey, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiMoveScreenTabFieldRequest struct {
	ctx context.Context
	ApiService *ScreenTabFieldsAPIService
	screenId int64
	tabId int64
	id string
	moveFieldBean *MoveFieldBean
}

func (r ApiMoveScreenTabFieldRequest) MoveFieldBean(moveFieldBean MoveFieldBean) ApiMoveScreenTabFieldRequest {
	r.moveFieldBean = &moveFieldBean
	return r
}

func (r ApiMoveScreenTabFieldRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.MoveScreenTabFieldExecute(r)
}

/*
MoveScreenTabField Move screen tab field

Moves a screen tab field.

If `after` and `position` are provided in the request, `position` is ignored.

**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param screenId The ID of the screen.
 @param tabId The ID of the screen tab.
 @param id The ID of the field.
 @return ApiMoveScreenTabFieldRequest
*/
func (a *ScreenTabFieldsAPIService) MoveScreenTabField(ctx context.Context, screenId int64, tabId int64, id string) ApiMoveScreenTabFieldRequest {
	return ApiMoveScreenTabFieldRequest{
		ApiService: a,
		ctx: ctx,
		screenId: screenId,
		tabId: tabId,
		id: id,
	}
}

// Execute executes the request
//  @return interface{}
func (a *ScreenTabFieldsAPIService) MoveScreenTabFieldExecute(r ApiMoveScreenTabFieldRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScreenTabFieldsAPIService.MoveScreenTabField")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/rest/api/3/screens/{screenId}/tabs/{tabId}/fields/{id}/move"
	localVarPath = strings.Replace(localVarPath, "{"+"screenId"+"}", url.PathEscape(parameterValueToString(r.screenId, "screenId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tabId"+"}", url.PathEscape(parameterValueToString(r.tabId, "tabId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.moveFieldBean == nil {
		return localVarReturnValue, nil, reportError("moveFieldBean is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.moveFieldBean
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRemoveScreenTabFieldRequest struct {
	ctx context.Context
	ApiService *ScreenTabFieldsAPIService
	screenId int64
	tabId int64
	id string
}

func (r ApiRemoveScreenTabFieldRequest) Execute() (*http.Response, error) {
	return r.ApiService.RemoveScreenTabFieldExecute(r)
}

/*
RemoveScreenTabField Remove screen tab field

Removes a field from a screen tab.

**[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param screenId The ID of the screen.
 @param tabId The ID of the screen tab.
 @param id The ID of the field.
 @return ApiRemoveScreenTabFieldRequest
*/
func (a *ScreenTabFieldsAPIService) RemoveScreenTabField(ctx context.Context, screenId int64, tabId int64, id string) ApiRemoveScreenTabFieldRequest {
	return ApiRemoveScreenTabFieldRequest{
		ApiService: a,
		ctx: ctx,
		screenId: screenId,
		tabId: tabId,
		id: id,
	}
}

// Execute executes the request
func (a *ScreenTabFieldsAPIService) RemoveScreenTabFieldExecute(r ApiRemoveScreenTabFieldRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ScreenTabFieldsAPIService.RemoveScreenTabField")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/rest/api/3/screens/{screenId}/tabs/{tabId}/fields/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"screenId"+"}", url.PathEscape(parameterValueToString(r.screenId, "screenId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tabId"+"}", url.PathEscape(parameterValueToString(r.tabId, "tabId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
