/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the JiraIssueFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JiraIssueFields{}

// JiraIssueFields struct for JiraIssueFields
type JiraIssueFields struct {
	// Add or clear a cascading select field:   *  To add, specify `optionId` for both parent and child.  *  To clear the child, set its `optionId` to null.  *  To clear both, set the parent's `optionId` to null.
	CascadingSelectFields []JiraCascadingSelectField `json:"cascadingSelectFields,omitempty"`
	// Add or clear a number field:   *  To add, specify a numeric `value`.  *  To clear, set `value` to `null`.
	ClearableNumberFields []JiraNumberField `json:"clearableNumberFields,omitempty"`
	// Add or clear a color field:   *  To add, specify the color `name`. Available colors are: `purple`, `blue`, `green`, `teal`, `yellow`, `orange`, `grey`, `dark purple`, `dark blue`, `dark green`, `dark teal`, `dark yellow`, `dark orange`, `dark grey`.  *  To clear, set the color `name` to an empty string.
	ColorFields []JiraColorField `json:"colorFields,omitempty"`
	// Add or clear a date picker field:   *  To add, specify the date in `d/mmm/yy` format or ISO format `dd-mm-yyyy`.  *  To clear, set `formattedDate` to an empty string.
	DatePickerFields []JiraDateField `json:"datePickerFields,omitempty"`
	// Add or clear the planned start date and time:   *  To add, specify the date and time in ISO format for `formattedDateTime`.  *  To clear, provide an empty string for `formattedDateTime`.
	DateTimePickerFields []JiraDateTimeField `json:"dateTimePickerFields,omitempty"`
	// Set the issue type field by providing an `issueTypeId`.
	IssueType *JiraIssueTypeField `json:"issueType,omitempty"`
	// Edit a labels field:   *  Options include `ADD`, `REPLACE`, `REMOVE`, or `REMOVE_ALL` for bulk edits.  *  To clear labels, use the `REMOVE_ALL` option with an empty `labels` array.
	LabelsFields []JiraLabelsField `json:"labelsFields,omitempty"`
	// Add or clear a multi-group picker field:   *  To add groups, provide an array of groups with `groupName`s.  *  To clear all groups, use an empty `groups` array.
	MultipleGroupPickerFields []JiraMultipleGroupPickerField `json:"multipleGroupPickerFields,omitempty"`
	// Assign or unassign multiple users to/from a field:   *  To assign, provide an array of user `accountId`s.  *  To clear, set `users` to `null`.
	MultipleSelectClearableUserPickerFields []JiraMultipleSelectUserPickerField `json:"multipleSelectClearableUserPickerFields,omitempty"`
	// Add or clear a multi-select field:   *  To add, provide an array of options with `optionId`s.  *  To clear, use an empty `options` array.
	MultipleSelectFields []JiraMultipleSelectField `json:"multipleSelectFields,omitempty"`
	// Edit a multi-version picker field like Fix Versions/Affects Versions:   *  Options include `ADD`, `REPLACE`, `REMOVE`, or `REMOVE_ALL` for bulk edits.  *  To clear the field, use the `REMOVE_ALL` option with an empty `versions` array.
	MultipleVersionPickerFields []JiraMultipleVersionPickerField `json:"multipleVersionPickerFields,omitempty"`
	// Edit a multi select components field:   *  Options include `ADD`, `REPLACE`, `REMOVE`, or `REMOVE_ALL` for bulk edits.  *  To clear, use the `REMOVE_ALL` option with an empty `components` array.
	MultiselectComponents *JiraMultiSelectComponentField `json:"multiselectComponents,omitempty"`
	// Edit the original estimate field.
	OriginalEstimateField *JiraDurationField `json:"originalEstimateField,omitempty"`
	// Set the priority of an issue by specifying a `priorityId`.
	Priority *JiraPriorityField `json:"priority,omitempty"`
	// Add or clear a rich text field:   *  To add, provide `adfValue`. Note that rich text fields only support ADF values.  *  To clear, use an empty `richText` object.  For ADF format details, refer to: [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure).
	RichTextFields []JiraRichTextField `json:"richTextFields,omitempty"`
	// Add or clear a single group picker field:   *  To add, specify the group with `groupName`.  *  To clear, set `groupName` to an empty string.
	SingleGroupPickerFields []JiraSingleGroupPickerField `json:"singleGroupPickerFields,omitempty"`
	// Add or clear a single line text field:   *  To add, provide the `text` value.  *  To clear, set `text` to an empty string.
	SingleLineTextFields []JiraSingleLineTextField `json:"singleLineTextFields,omitempty"`
	// Edit assignment for single select user picker fields like Assignee/Reporter:   *  To assign an issue, specify the user's `accountId`.  *  To unassign an issue, set `user` to `null`.  *  For automatic assignment, set `accountId` to `-1`.
	SingleSelectClearableUserPickerFields []JiraSingleSelectUserPickerField `json:"singleSelectClearableUserPickerFields,omitempty"`
	// Add or clear a single select field:   *  To add, specify the option with an `optionId`.  *  To clear, pass an option with `optionId` as `-1`.
	SingleSelectFields []JiraSingleSelectField `json:"singleSelectFields,omitempty"`
	// Add or clear a single version picker field:   *  To add, specify the version with a `versionId`.  *  To clear, set `versionId` to `-1`.
	SingleVersionPickerFields []JiraSingleVersionPickerField `json:"singleVersionPickerFields,omitempty"`
	Status *JiraStatusInput `json:"status,omitempty"`
	// Edit the time tracking field.
	TimeTrackingField *JiraTimeTrackingField `json:"timeTrackingField,omitempty"`
	// Add or clear a URL field:   *  To add, provide the `url` with the desired URL value.  *  To clear, set `url` to an empty string.
	UrlFields []JiraUrlField `json:"urlFields,omitempty"`
}

// NewJiraIssueFields instantiates a new JiraIssueFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJiraIssueFields() *JiraIssueFields {
	this := JiraIssueFields{}
	return &this
}

// NewJiraIssueFieldsWithDefaults instantiates a new JiraIssueFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJiraIssueFieldsWithDefaults() *JiraIssueFields {
	this := JiraIssueFields{}
	return &this
}

// GetCascadingSelectFields returns the CascadingSelectFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetCascadingSelectFields() []JiraCascadingSelectField {
	if o == nil || IsNil(o.CascadingSelectFields) {
		var ret []JiraCascadingSelectField
		return ret
	}
	return o.CascadingSelectFields
}

// GetCascadingSelectFieldsOk returns a tuple with the CascadingSelectFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetCascadingSelectFieldsOk() ([]JiraCascadingSelectField, bool) {
	if o == nil || IsNil(o.CascadingSelectFields) {
		return nil, false
	}
	return o.CascadingSelectFields, true
}

// HasCascadingSelectFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasCascadingSelectFields() bool {
	if o != nil && !IsNil(o.CascadingSelectFields) {
		return true
	}

	return false
}

// SetCascadingSelectFields gets a reference to the given []JiraCascadingSelectField and assigns it to the CascadingSelectFields field.
func (o *JiraIssueFields) SetCascadingSelectFields(v []JiraCascadingSelectField) {
	o.CascadingSelectFields = v
}

// GetClearableNumberFields returns the ClearableNumberFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetClearableNumberFields() []JiraNumberField {
	if o == nil || IsNil(o.ClearableNumberFields) {
		var ret []JiraNumberField
		return ret
	}
	return o.ClearableNumberFields
}

// GetClearableNumberFieldsOk returns a tuple with the ClearableNumberFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetClearableNumberFieldsOk() ([]JiraNumberField, bool) {
	if o == nil || IsNil(o.ClearableNumberFields) {
		return nil, false
	}
	return o.ClearableNumberFields, true
}

// HasClearableNumberFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasClearableNumberFields() bool {
	if o != nil && !IsNil(o.ClearableNumberFields) {
		return true
	}

	return false
}

// SetClearableNumberFields gets a reference to the given []JiraNumberField and assigns it to the ClearableNumberFields field.
func (o *JiraIssueFields) SetClearableNumberFields(v []JiraNumberField) {
	o.ClearableNumberFields = v
}

// GetColorFields returns the ColorFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetColorFields() []JiraColorField {
	if o == nil || IsNil(o.ColorFields) {
		var ret []JiraColorField
		return ret
	}
	return o.ColorFields
}

// GetColorFieldsOk returns a tuple with the ColorFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetColorFieldsOk() ([]JiraColorField, bool) {
	if o == nil || IsNil(o.ColorFields) {
		return nil, false
	}
	return o.ColorFields, true
}

// HasColorFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasColorFields() bool {
	if o != nil && !IsNil(o.ColorFields) {
		return true
	}

	return false
}

// SetColorFields gets a reference to the given []JiraColorField and assigns it to the ColorFields field.
func (o *JiraIssueFields) SetColorFields(v []JiraColorField) {
	o.ColorFields = v
}

// GetDatePickerFields returns the DatePickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetDatePickerFields() []JiraDateField {
	if o == nil || IsNil(o.DatePickerFields) {
		var ret []JiraDateField
		return ret
	}
	return o.DatePickerFields
}

// GetDatePickerFieldsOk returns a tuple with the DatePickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetDatePickerFieldsOk() ([]JiraDateField, bool) {
	if o == nil || IsNil(o.DatePickerFields) {
		return nil, false
	}
	return o.DatePickerFields, true
}

// HasDatePickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasDatePickerFields() bool {
	if o != nil && !IsNil(o.DatePickerFields) {
		return true
	}

	return false
}

// SetDatePickerFields gets a reference to the given []JiraDateField and assigns it to the DatePickerFields field.
func (o *JiraIssueFields) SetDatePickerFields(v []JiraDateField) {
	o.DatePickerFields = v
}

// GetDateTimePickerFields returns the DateTimePickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetDateTimePickerFields() []JiraDateTimeField {
	if o == nil || IsNil(o.DateTimePickerFields) {
		var ret []JiraDateTimeField
		return ret
	}
	return o.DateTimePickerFields
}

// GetDateTimePickerFieldsOk returns a tuple with the DateTimePickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetDateTimePickerFieldsOk() ([]JiraDateTimeField, bool) {
	if o == nil || IsNil(o.DateTimePickerFields) {
		return nil, false
	}
	return o.DateTimePickerFields, true
}

// HasDateTimePickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasDateTimePickerFields() bool {
	if o != nil && !IsNil(o.DateTimePickerFields) {
		return true
	}

	return false
}

// SetDateTimePickerFields gets a reference to the given []JiraDateTimeField and assigns it to the DateTimePickerFields field.
func (o *JiraIssueFields) SetDateTimePickerFields(v []JiraDateTimeField) {
	o.DateTimePickerFields = v
}

// GetIssueType returns the IssueType field value if set, zero value otherwise.
func (o *JiraIssueFields) GetIssueType() JiraIssueTypeField {
	if o == nil || IsNil(o.IssueType) {
		var ret JiraIssueTypeField
		return ret
	}
	return *o.IssueType
}

// GetIssueTypeOk returns a tuple with the IssueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetIssueTypeOk() (*JiraIssueTypeField, bool) {
	if o == nil || IsNil(o.IssueType) {
		return nil, false
	}
	return o.IssueType, true
}

// HasIssueType returns a boolean if a field has been set.
func (o *JiraIssueFields) HasIssueType() bool {
	if o != nil && !IsNil(o.IssueType) {
		return true
	}

	return false
}

// SetIssueType gets a reference to the given JiraIssueTypeField and assigns it to the IssueType field.
func (o *JiraIssueFields) SetIssueType(v JiraIssueTypeField) {
	o.IssueType = &v
}

// GetLabelsFields returns the LabelsFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetLabelsFields() []JiraLabelsField {
	if o == nil || IsNil(o.LabelsFields) {
		var ret []JiraLabelsField
		return ret
	}
	return o.LabelsFields
}

// GetLabelsFieldsOk returns a tuple with the LabelsFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetLabelsFieldsOk() ([]JiraLabelsField, bool) {
	if o == nil || IsNil(o.LabelsFields) {
		return nil, false
	}
	return o.LabelsFields, true
}

// HasLabelsFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasLabelsFields() bool {
	if o != nil && !IsNil(o.LabelsFields) {
		return true
	}

	return false
}

// SetLabelsFields gets a reference to the given []JiraLabelsField and assigns it to the LabelsFields field.
func (o *JiraIssueFields) SetLabelsFields(v []JiraLabelsField) {
	o.LabelsFields = v
}

// GetMultipleGroupPickerFields returns the MultipleGroupPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetMultipleGroupPickerFields() []JiraMultipleGroupPickerField {
	if o == nil || IsNil(o.MultipleGroupPickerFields) {
		var ret []JiraMultipleGroupPickerField
		return ret
	}
	return o.MultipleGroupPickerFields
}

// GetMultipleGroupPickerFieldsOk returns a tuple with the MultipleGroupPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetMultipleGroupPickerFieldsOk() ([]JiraMultipleGroupPickerField, bool) {
	if o == nil || IsNil(o.MultipleGroupPickerFields) {
		return nil, false
	}
	return o.MultipleGroupPickerFields, true
}

// HasMultipleGroupPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasMultipleGroupPickerFields() bool {
	if o != nil && !IsNil(o.MultipleGroupPickerFields) {
		return true
	}

	return false
}

// SetMultipleGroupPickerFields gets a reference to the given []JiraMultipleGroupPickerField and assigns it to the MultipleGroupPickerFields field.
func (o *JiraIssueFields) SetMultipleGroupPickerFields(v []JiraMultipleGroupPickerField) {
	o.MultipleGroupPickerFields = v
}

// GetMultipleSelectClearableUserPickerFields returns the MultipleSelectClearableUserPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetMultipleSelectClearableUserPickerFields() []JiraMultipleSelectUserPickerField {
	if o == nil || IsNil(o.MultipleSelectClearableUserPickerFields) {
		var ret []JiraMultipleSelectUserPickerField
		return ret
	}
	return o.MultipleSelectClearableUserPickerFields
}

// GetMultipleSelectClearableUserPickerFieldsOk returns a tuple with the MultipleSelectClearableUserPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetMultipleSelectClearableUserPickerFieldsOk() ([]JiraMultipleSelectUserPickerField, bool) {
	if o == nil || IsNil(o.MultipleSelectClearableUserPickerFields) {
		return nil, false
	}
	return o.MultipleSelectClearableUserPickerFields, true
}

// HasMultipleSelectClearableUserPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasMultipleSelectClearableUserPickerFields() bool {
	if o != nil && !IsNil(o.MultipleSelectClearableUserPickerFields) {
		return true
	}

	return false
}

// SetMultipleSelectClearableUserPickerFields gets a reference to the given []JiraMultipleSelectUserPickerField and assigns it to the MultipleSelectClearableUserPickerFields field.
func (o *JiraIssueFields) SetMultipleSelectClearableUserPickerFields(v []JiraMultipleSelectUserPickerField) {
	o.MultipleSelectClearableUserPickerFields = v
}

// GetMultipleSelectFields returns the MultipleSelectFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetMultipleSelectFields() []JiraMultipleSelectField {
	if o == nil || IsNil(o.MultipleSelectFields) {
		var ret []JiraMultipleSelectField
		return ret
	}
	return o.MultipleSelectFields
}

// GetMultipleSelectFieldsOk returns a tuple with the MultipleSelectFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetMultipleSelectFieldsOk() ([]JiraMultipleSelectField, bool) {
	if o == nil || IsNil(o.MultipleSelectFields) {
		return nil, false
	}
	return o.MultipleSelectFields, true
}

// HasMultipleSelectFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasMultipleSelectFields() bool {
	if o != nil && !IsNil(o.MultipleSelectFields) {
		return true
	}

	return false
}

// SetMultipleSelectFields gets a reference to the given []JiraMultipleSelectField and assigns it to the MultipleSelectFields field.
func (o *JiraIssueFields) SetMultipleSelectFields(v []JiraMultipleSelectField) {
	o.MultipleSelectFields = v
}

// GetMultipleVersionPickerFields returns the MultipleVersionPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetMultipleVersionPickerFields() []JiraMultipleVersionPickerField {
	if o == nil || IsNil(o.MultipleVersionPickerFields) {
		var ret []JiraMultipleVersionPickerField
		return ret
	}
	return o.MultipleVersionPickerFields
}

// GetMultipleVersionPickerFieldsOk returns a tuple with the MultipleVersionPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetMultipleVersionPickerFieldsOk() ([]JiraMultipleVersionPickerField, bool) {
	if o == nil || IsNil(o.MultipleVersionPickerFields) {
		return nil, false
	}
	return o.MultipleVersionPickerFields, true
}

// HasMultipleVersionPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasMultipleVersionPickerFields() bool {
	if o != nil && !IsNil(o.MultipleVersionPickerFields) {
		return true
	}

	return false
}

// SetMultipleVersionPickerFields gets a reference to the given []JiraMultipleVersionPickerField and assigns it to the MultipleVersionPickerFields field.
func (o *JiraIssueFields) SetMultipleVersionPickerFields(v []JiraMultipleVersionPickerField) {
	o.MultipleVersionPickerFields = v
}

// GetMultiselectComponents returns the MultiselectComponents field value if set, zero value otherwise.
func (o *JiraIssueFields) GetMultiselectComponents() JiraMultiSelectComponentField {
	if o == nil || IsNil(o.MultiselectComponents) {
		var ret JiraMultiSelectComponentField
		return ret
	}
	return *o.MultiselectComponents
}

// GetMultiselectComponentsOk returns a tuple with the MultiselectComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetMultiselectComponentsOk() (*JiraMultiSelectComponentField, bool) {
	if o == nil || IsNil(o.MultiselectComponents) {
		return nil, false
	}
	return o.MultiselectComponents, true
}

// HasMultiselectComponents returns a boolean if a field has been set.
func (o *JiraIssueFields) HasMultiselectComponents() bool {
	if o != nil && !IsNil(o.MultiselectComponents) {
		return true
	}

	return false
}

// SetMultiselectComponents gets a reference to the given JiraMultiSelectComponentField and assigns it to the MultiselectComponents field.
func (o *JiraIssueFields) SetMultiselectComponents(v JiraMultiSelectComponentField) {
	o.MultiselectComponents = &v
}

// GetOriginalEstimateField returns the OriginalEstimateField field value if set, zero value otherwise.
func (o *JiraIssueFields) GetOriginalEstimateField() JiraDurationField {
	if o == nil || IsNil(o.OriginalEstimateField) {
		var ret JiraDurationField
		return ret
	}
	return *o.OriginalEstimateField
}

// GetOriginalEstimateFieldOk returns a tuple with the OriginalEstimateField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetOriginalEstimateFieldOk() (*JiraDurationField, bool) {
	if o == nil || IsNil(o.OriginalEstimateField) {
		return nil, false
	}
	return o.OriginalEstimateField, true
}

// HasOriginalEstimateField returns a boolean if a field has been set.
func (o *JiraIssueFields) HasOriginalEstimateField() bool {
	if o != nil && !IsNil(o.OriginalEstimateField) {
		return true
	}

	return false
}

// SetOriginalEstimateField gets a reference to the given JiraDurationField and assigns it to the OriginalEstimateField field.
func (o *JiraIssueFields) SetOriginalEstimateField(v JiraDurationField) {
	o.OriginalEstimateField = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *JiraIssueFields) GetPriority() JiraPriorityField {
	if o == nil || IsNil(o.Priority) {
		var ret JiraPriorityField
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetPriorityOk() (*JiraPriorityField, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *JiraIssueFields) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given JiraPriorityField and assigns it to the Priority field.
func (o *JiraIssueFields) SetPriority(v JiraPriorityField) {
	o.Priority = &v
}

// GetRichTextFields returns the RichTextFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetRichTextFields() []JiraRichTextField {
	if o == nil || IsNil(o.RichTextFields) {
		var ret []JiraRichTextField
		return ret
	}
	return o.RichTextFields
}

// GetRichTextFieldsOk returns a tuple with the RichTextFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetRichTextFieldsOk() ([]JiraRichTextField, bool) {
	if o == nil || IsNil(o.RichTextFields) {
		return nil, false
	}
	return o.RichTextFields, true
}

// HasRichTextFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasRichTextFields() bool {
	if o != nil && !IsNil(o.RichTextFields) {
		return true
	}

	return false
}

// SetRichTextFields gets a reference to the given []JiraRichTextField and assigns it to the RichTextFields field.
func (o *JiraIssueFields) SetRichTextFields(v []JiraRichTextField) {
	o.RichTextFields = v
}

// GetSingleGroupPickerFields returns the SingleGroupPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetSingleGroupPickerFields() []JiraSingleGroupPickerField {
	if o == nil || IsNil(o.SingleGroupPickerFields) {
		var ret []JiraSingleGroupPickerField
		return ret
	}
	return o.SingleGroupPickerFields
}

// GetSingleGroupPickerFieldsOk returns a tuple with the SingleGroupPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetSingleGroupPickerFieldsOk() ([]JiraSingleGroupPickerField, bool) {
	if o == nil || IsNil(o.SingleGroupPickerFields) {
		return nil, false
	}
	return o.SingleGroupPickerFields, true
}

// HasSingleGroupPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasSingleGroupPickerFields() bool {
	if o != nil && !IsNil(o.SingleGroupPickerFields) {
		return true
	}

	return false
}

// SetSingleGroupPickerFields gets a reference to the given []JiraSingleGroupPickerField and assigns it to the SingleGroupPickerFields field.
func (o *JiraIssueFields) SetSingleGroupPickerFields(v []JiraSingleGroupPickerField) {
	o.SingleGroupPickerFields = v
}

// GetSingleLineTextFields returns the SingleLineTextFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetSingleLineTextFields() []JiraSingleLineTextField {
	if o == nil || IsNil(o.SingleLineTextFields) {
		var ret []JiraSingleLineTextField
		return ret
	}
	return o.SingleLineTextFields
}

// GetSingleLineTextFieldsOk returns a tuple with the SingleLineTextFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetSingleLineTextFieldsOk() ([]JiraSingleLineTextField, bool) {
	if o == nil || IsNil(o.SingleLineTextFields) {
		return nil, false
	}
	return o.SingleLineTextFields, true
}

// HasSingleLineTextFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasSingleLineTextFields() bool {
	if o != nil && !IsNil(o.SingleLineTextFields) {
		return true
	}

	return false
}

// SetSingleLineTextFields gets a reference to the given []JiraSingleLineTextField and assigns it to the SingleLineTextFields field.
func (o *JiraIssueFields) SetSingleLineTextFields(v []JiraSingleLineTextField) {
	o.SingleLineTextFields = v
}

// GetSingleSelectClearableUserPickerFields returns the SingleSelectClearableUserPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetSingleSelectClearableUserPickerFields() []JiraSingleSelectUserPickerField {
	if o == nil || IsNil(o.SingleSelectClearableUserPickerFields) {
		var ret []JiraSingleSelectUserPickerField
		return ret
	}
	return o.SingleSelectClearableUserPickerFields
}

// GetSingleSelectClearableUserPickerFieldsOk returns a tuple with the SingleSelectClearableUserPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetSingleSelectClearableUserPickerFieldsOk() ([]JiraSingleSelectUserPickerField, bool) {
	if o == nil || IsNil(o.SingleSelectClearableUserPickerFields) {
		return nil, false
	}
	return o.SingleSelectClearableUserPickerFields, true
}

// HasSingleSelectClearableUserPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasSingleSelectClearableUserPickerFields() bool {
	if o != nil && !IsNil(o.SingleSelectClearableUserPickerFields) {
		return true
	}

	return false
}

// SetSingleSelectClearableUserPickerFields gets a reference to the given []JiraSingleSelectUserPickerField and assigns it to the SingleSelectClearableUserPickerFields field.
func (o *JiraIssueFields) SetSingleSelectClearableUserPickerFields(v []JiraSingleSelectUserPickerField) {
	o.SingleSelectClearableUserPickerFields = v
}

// GetSingleSelectFields returns the SingleSelectFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetSingleSelectFields() []JiraSingleSelectField {
	if o == nil || IsNil(o.SingleSelectFields) {
		var ret []JiraSingleSelectField
		return ret
	}
	return o.SingleSelectFields
}

// GetSingleSelectFieldsOk returns a tuple with the SingleSelectFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetSingleSelectFieldsOk() ([]JiraSingleSelectField, bool) {
	if o == nil || IsNil(o.SingleSelectFields) {
		return nil, false
	}
	return o.SingleSelectFields, true
}

// HasSingleSelectFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasSingleSelectFields() bool {
	if o != nil && !IsNil(o.SingleSelectFields) {
		return true
	}

	return false
}

// SetSingleSelectFields gets a reference to the given []JiraSingleSelectField and assigns it to the SingleSelectFields field.
func (o *JiraIssueFields) SetSingleSelectFields(v []JiraSingleSelectField) {
	o.SingleSelectFields = v
}

// GetSingleVersionPickerFields returns the SingleVersionPickerFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetSingleVersionPickerFields() []JiraSingleVersionPickerField {
	if o == nil || IsNil(o.SingleVersionPickerFields) {
		var ret []JiraSingleVersionPickerField
		return ret
	}
	return o.SingleVersionPickerFields
}

// GetSingleVersionPickerFieldsOk returns a tuple with the SingleVersionPickerFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetSingleVersionPickerFieldsOk() ([]JiraSingleVersionPickerField, bool) {
	if o == nil || IsNil(o.SingleVersionPickerFields) {
		return nil, false
	}
	return o.SingleVersionPickerFields, true
}

// HasSingleVersionPickerFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasSingleVersionPickerFields() bool {
	if o != nil && !IsNil(o.SingleVersionPickerFields) {
		return true
	}

	return false
}

// SetSingleVersionPickerFields gets a reference to the given []JiraSingleVersionPickerField and assigns it to the SingleVersionPickerFields field.
func (o *JiraIssueFields) SetSingleVersionPickerFields(v []JiraSingleVersionPickerField) {
	o.SingleVersionPickerFields = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *JiraIssueFields) GetStatus() JiraStatusInput {
	if o == nil || IsNil(o.Status) {
		var ret JiraStatusInput
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetStatusOk() (*JiraStatusInput, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *JiraIssueFields) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given JiraStatusInput and assigns it to the Status field.
func (o *JiraIssueFields) SetStatus(v JiraStatusInput) {
	o.Status = &v
}

// GetTimeTrackingField returns the TimeTrackingField field value if set, zero value otherwise.
func (o *JiraIssueFields) GetTimeTrackingField() JiraTimeTrackingField {
	if o == nil || IsNil(o.TimeTrackingField) {
		var ret JiraTimeTrackingField
		return ret
	}
	return *o.TimeTrackingField
}

// GetTimeTrackingFieldOk returns a tuple with the TimeTrackingField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetTimeTrackingFieldOk() (*JiraTimeTrackingField, bool) {
	if o == nil || IsNil(o.TimeTrackingField) {
		return nil, false
	}
	return o.TimeTrackingField, true
}

// HasTimeTrackingField returns a boolean if a field has been set.
func (o *JiraIssueFields) HasTimeTrackingField() bool {
	if o != nil && !IsNil(o.TimeTrackingField) {
		return true
	}

	return false
}

// SetTimeTrackingField gets a reference to the given JiraTimeTrackingField and assigns it to the TimeTrackingField field.
func (o *JiraIssueFields) SetTimeTrackingField(v JiraTimeTrackingField) {
	o.TimeTrackingField = &v
}

// GetUrlFields returns the UrlFields field value if set, zero value otherwise.
func (o *JiraIssueFields) GetUrlFields() []JiraUrlField {
	if o == nil || IsNil(o.UrlFields) {
		var ret []JiraUrlField
		return ret
	}
	return o.UrlFields
}

// GetUrlFieldsOk returns a tuple with the UrlFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraIssueFields) GetUrlFieldsOk() ([]JiraUrlField, bool) {
	if o == nil || IsNil(o.UrlFields) {
		return nil, false
	}
	return o.UrlFields, true
}

// HasUrlFields returns a boolean if a field has been set.
func (o *JiraIssueFields) HasUrlFields() bool {
	if o != nil && !IsNil(o.UrlFields) {
		return true
	}

	return false
}

// SetUrlFields gets a reference to the given []JiraUrlField and assigns it to the UrlFields field.
func (o *JiraIssueFields) SetUrlFields(v []JiraUrlField) {
	o.UrlFields = v
}

func (o JiraIssueFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JiraIssueFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CascadingSelectFields) {
		toSerialize["cascadingSelectFields"] = o.CascadingSelectFields
	}
	if !IsNil(o.ClearableNumberFields) {
		toSerialize["clearableNumberFields"] = o.ClearableNumberFields
	}
	if !IsNil(o.ColorFields) {
		toSerialize["colorFields"] = o.ColorFields
	}
	if !IsNil(o.DatePickerFields) {
		toSerialize["datePickerFields"] = o.DatePickerFields
	}
	if !IsNil(o.DateTimePickerFields) {
		toSerialize["dateTimePickerFields"] = o.DateTimePickerFields
	}
	if !IsNil(o.IssueType) {
		toSerialize["issueType"] = o.IssueType
	}
	if !IsNil(o.LabelsFields) {
		toSerialize["labelsFields"] = o.LabelsFields
	}
	if !IsNil(o.MultipleGroupPickerFields) {
		toSerialize["multipleGroupPickerFields"] = o.MultipleGroupPickerFields
	}
	if !IsNil(o.MultipleSelectClearableUserPickerFields) {
		toSerialize["multipleSelectClearableUserPickerFields"] = o.MultipleSelectClearableUserPickerFields
	}
	if !IsNil(o.MultipleSelectFields) {
		toSerialize["multipleSelectFields"] = o.MultipleSelectFields
	}
	if !IsNil(o.MultipleVersionPickerFields) {
		toSerialize["multipleVersionPickerFields"] = o.MultipleVersionPickerFields
	}
	if !IsNil(o.MultiselectComponents) {
		toSerialize["multiselectComponents"] = o.MultiselectComponents
	}
	if !IsNil(o.OriginalEstimateField) {
		toSerialize["originalEstimateField"] = o.OriginalEstimateField
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.RichTextFields) {
		toSerialize["richTextFields"] = o.RichTextFields
	}
	if !IsNil(o.SingleGroupPickerFields) {
		toSerialize["singleGroupPickerFields"] = o.SingleGroupPickerFields
	}
	if !IsNil(o.SingleLineTextFields) {
		toSerialize["singleLineTextFields"] = o.SingleLineTextFields
	}
	if !IsNil(o.SingleSelectClearableUserPickerFields) {
		toSerialize["singleSelectClearableUserPickerFields"] = o.SingleSelectClearableUserPickerFields
	}
	if !IsNil(o.SingleSelectFields) {
		toSerialize["singleSelectFields"] = o.SingleSelectFields
	}
	if !IsNil(o.SingleVersionPickerFields) {
		toSerialize["singleVersionPickerFields"] = o.SingleVersionPickerFields
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TimeTrackingField) {
		toSerialize["timeTrackingField"] = o.TimeTrackingField
	}
	if !IsNil(o.UrlFields) {
		toSerialize["urlFields"] = o.UrlFields
	}
	return toSerialize, nil
}

type NullableJiraIssueFields struct {
	value *JiraIssueFields
	isSet bool
}

func (v NullableJiraIssueFields) Get() *JiraIssueFields {
	return v.value
}

func (v *NullableJiraIssueFields) Set(val *JiraIssueFields) {
	v.value = val
	v.isSet = true
}

func (v NullableJiraIssueFields) IsSet() bool {
	return v.isSet
}

func (v *NullableJiraIssueFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJiraIssueFields(val *JiraIssueFields) *NullableJiraIssueFields {
	return &NullableJiraIssueFields{value: val, isSet: true}
}

func (v NullableJiraIssueFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJiraIssueFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


