/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the Votes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Votes{}

// Votes The details of votes on an issue.
type Votes struct {
	// Whether the user making this request has voted on the issue.
	HasVoted *bool `json:"hasVoted,omitempty"`
	// The URL of these issue vote details.
	Self *string `json:"self,omitempty"`
	// List of the users who have voted on this issue. An empty list is returned when the calling user doesn't have the *View voters and watchers* project permission.
	Voters []User `json:"voters,omitempty"`
	// The number of votes on the issue.
	Votes *int64 `json:"votes,omitempty"`
}

// NewVotes instantiates a new Votes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVotes() *Votes {
	this := Votes{}
	return &this
}

// NewVotesWithDefaults instantiates a new Votes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVotesWithDefaults() *Votes {
	this := Votes{}
	return &this
}

// GetHasVoted returns the HasVoted field value if set, zero value otherwise.
func (o *Votes) GetHasVoted() bool {
	if o == nil || IsNil(o.HasVoted) {
		var ret bool
		return ret
	}
	return *o.HasVoted
}

// GetHasVotedOk returns a tuple with the HasVoted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Votes) GetHasVotedOk() (*bool, bool) {
	if o == nil || IsNil(o.HasVoted) {
		return nil, false
	}
	return o.HasVoted, true
}

// HasHasVoted returns a boolean if a field has been set.
func (o *Votes) HasHasVoted() bool {
	if o != nil && !IsNil(o.HasVoted) {
		return true
	}

	return false
}

// SetHasVoted gets a reference to the given bool and assigns it to the HasVoted field.
func (o *Votes) SetHasVoted(v bool) {
	o.HasVoted = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *Votes) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Votes) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *Votes) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *Votes) SetSelf(v string) {
	o.Self = &v
}

// GetVoters returns the Voters field value if set, zero value otherwise.
func (o *Votes) GetVoters() []User {
	if o == nil || IsNil(o.Voters) {
		var ret []User
		return ret
	}
	return o.Voters
}

// GetVotersOk returns a tuple with the Voters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Votes) GetVotersOk() ([]User, bool) {
	if o == nil || IsNil(o.Voters) {
		return nil, false
	}
	return o.Voters, true
}

// HasVoters returns a boolean if a field has been set.
func (o *Votes) HasVoters() bool {
	if o != nil && !IsNil(o.Voters) {
		return true
	}

	return false
}

// SetVoters gets a reference to the given []User and assigns it to the Voters field.
func (o *Votes) SetVoters(v []User) {
	o.Voters = v
}

// GetVotes returns the Votes field value if set, zero value otherwise.
func (o *Votes) GetVotes() int64 {
	if o == nil || IsNil(o.Votes) {
		var ret int64
		return ret
	}
	return *o.Votes
}

// GetVotesOk returns a tuple with the Votes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Votes) GetVotesOk() (*int64, bool) {
	if o == nil || IsNil(o.Votes) {
		return nil, false
	}
	return o.Votes, true
}

// HasVotes returns a boolean if a field has been set.
func (o *Votes) HasVotes() bool {
	if o != nil && !IsNil(o.Votes) {
		return true
	}

	return false
}

// SetVotes gets a reference to the given int64 and assigns it to the Votes field.
func (o *Votes) SetVotes(v int64) {
	o.Votes = &v
}

func (o Votes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Votes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasVoted) {
		toSerialize["hasVoted"] = o.HasVoted
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Voters) {
		toSerialize["voters"] = o.Voters
	}
	if !IsNil(o.Votes) {
		toSerialize["votes"] = o.Votes
	}
	return toSerialize, nil
}

type NullableVotes struct {
	value *Votes
	isSet bool
}

func (v NullableVotes) Get() *Votes {
	return v.value
}

func (v *NullableVotes) Set(val *Votes) {
	v.value = val
	v.isSet = true
}

func (v NullableVotes) IsSet() bool {
	return v.isSet
}

func (v *NullableVotes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVotes(val *Votes) *NullableVotes {
	return &NullableVotes{value: val, isSet: true}
}

func (v NullableVotes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVotes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


