/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the AuditRecords type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditRecords{}

// AuditRecords Container for a list of audit records.
type AuditRecords struct {
	// The requested or default limit on the number of audit items to be returned.
	Limit *int32 `json:"limit,omitempty"`
	// The number of audit items skipped before the first item in this list.
	Offset *int32 `json:"offset,omitempty"`
	// The list of audit items.
	Records []AuditRecordBean `json:"records,omitempty"`
	// The total number of audit items returned.
	Total *int64 `json:"total,omitempty"`
}

// NewAuditRecords instantiates a new AuditRecords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditRecords() *AuditRecords {
	this := AuditRecords{}
	return &this
}

// NewAuditRecordsWithDefaults instantiates a new AuditRecords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditRecordsWithDefaults() *AuditRecords {
	this := AuditRecords{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *AuditRecords) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditRecords) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *AuditRecords) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *AuditRecords) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *AuditRecords) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditRecords) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *AuditRecords) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *AuditRecords) SetOffset(v int32) {
	o.Offset = &v
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *AuditRecords) GetRecords() []AuditRecordBean {
	if o == nil || IsNil(o.Records) {
		var ret []AuditRecordBean
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditRecords) GetRecordsOk() ([]AuditRecordBean, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *AuditRecords) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []AuditRecordBean and assigns it to the Records field.
func (o *AuditRecords) SetRecords(v []AuditRecordBean) {
	o.Records = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AuditRecords) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditRecords) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AuditRecords) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *AuditRecords) SetTotal(v int64) {
	o.Total = &v
}

func (o AuditRecords) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditRecords) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAuditRecords struct {
	value *AuditRecords
	isSet bool
}

func (v NullableAuditRecords) Get() *AuditRecords {
	return v.value
}

func (v *NullableAuditRecords) Set(val *AuditRecords) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditRecords) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditRecords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditRecords(val *AuditRecords) *NullableAuditRecords {
	return &NullableAuditRecords{value: val, isSet: true}
}

func (v NullableAuditRecords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditRecords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


