/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The scope of the status.
type StatusScope struct {
	Project *ProjectId `json:"project,omitempty"`
	// The scope of the status. `GLOBAL` for company-managed projects and `PROJECT` for team-managed projects.
	Type_ string `json:"type"`
}
