/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectId{}

// ProjectId Project ID details.
type ProjectId struct {
	// The ID of the project.
	Id string `json:"id"`
}

type _ProjectId ProjectId

// NewProjectId instantiates a new ProjectId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectId(id string) *ProjectId {
	this := ProjectId{}
	this.Id = id
	return &this
}

// NewProjectIdWithDefaults instantiates a new ProjectId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectIdWithDefaults() *ProjectId {
	this := ProjectId{}
	return &this
}

// GetId returns the Id field value
func (o *ProjectId) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectId) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectId) SetId(v string) {
	o.Id = v
}

func (o ProjectId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ProjectId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectId := _ProjectId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectId)

	if err != nil {
		return err
	}

	*o = ProjectId(varProjectId)

	return err
}

type NullableProjectId struct {
	value *ProjectId
	isSet bool
}

func (v NullableProjectId) Get() *ProjectId {
	return v.value
}

func (v *NullableProjectId) Set(val *ProjectId) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectId) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectId(val *ProjectId) *NullableProjectId {
	return &NullableProjectId{value: val, isSet: true}
}

func (v NullableProjectId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


