/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomFieldOptionUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldOptionUpdate{}

// CustomFieldOptionUpdate Details of a custom field option for a context.
type CustomFieldOptionUpdate struct {
	// Whether the option is disabled.
	Disabled *bool `json:"disabled,omitempty"`
	// The ID of the custom field option.
	Id string `json:"id"`
	// The value of the custom field option.
	Value *string `json:"value,omitempty"`
}

type _CustomFieldOptionUpdate CustomFieldOptionUpdate

// NewCustomFieldOptionUpdate instantiates a new CustomFieldOptionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldOptionUpdate(id string) *CustomFieldOptionUpdate {
	this := CustomFieldOptionUpdate{}
	this.Id = id
	return &this
}

// NewCustomFieldOptionUpdateWithDefaults instantiates a new CustomFieldOptionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldOptionUpdateWithDefaults() *CustomFieldOptionUpdate {
	this := CustomFieldOptionUpdate{}
	return &this
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *CustomFieldOptionUpdate) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOptionUpdate) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *CustomFieldOptionUpdate) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *CustomFieldOptionUpdate) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetId returns the Id field value
func (o *CustomFieldOptionUpdate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomFieldOptionUpdate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomFieldOptionUpdate) SetId(v string) {
	o.Id = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CustomFieldOptionUpdate) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOptionUpdate) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CustomFieldOptionUpdate) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CustomFieldOptionUpdate) SetValue(v string) {
	o.Value = &v
}

func (o CustomFieldOptionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldOptionUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

func (o *CustomFieldOptionUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomFieldOptionUpdate := _CustomFieldOptionUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomFieldOptionUpdate)

	if err != nil {
		return err
	}

	*o = CustomFieldOptionUpdate(varCustomFieldOptionUpdate)

	return err
}

type NullableCustomFieldOptionUpdate struct {
	value *CustomFieldOptionUpdate
	isSet bool
}

func (v NullableCustomFieldOptionUpdate) Get() *CustomFieldOptionUpdate {
	return v.value
}

func (v *NullableCustomFieldOptionUpdate) Set(val *CustomFieldOptionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldOptionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldOptionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldOptionUpdate(val *CustomFieldOptionUpdate) *NullableCustomFieldOptionUpdate {
	return &NullableCustomFieldOptionUpdate{value: val, isSet: true}
}

func (v NullableCustomFieldOptionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldOptionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


