/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AttachmentArchive struct {
	Entries []AttachmentArchiveEntry `json:"entries,omitempty"`
	MoreAvailable bool `json:"moreAvailable,omitempty"`
	TotalEntryCount int32 `json:"totalEntryCount,omitempty"`
	TotalNumberOfEntriesAvailable int32 `json:"totalNumberOfEntriesAvailable,omitempty"`
}
