/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"fmt"
)

// checks if the NotificationSchemeEventDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationSchemeEventDetails{}

// NotificationSchemeEventDetails Details of a notification scheme event.
type NotificationSchemeEventDetails struct {
	// The ID of the event.
	Event NotificationSchemeEventTypeId `json:"event"`
	// The list of notifications mapped to a specified event.
	Notifications []NotificationSchemeNotificationDetails `json:"notifications"`
	AdditionalProperties map[string]interface{}
}

type _NotificationSchemeEventDetails NotificationSchemeEventDetails

// NewNotificationSchemeEventDetails instantiates a new NotificationSchemeEventDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationSchemeEventDetails(event NotificationSchemeEventTypeId, notifications []NotificationSchemeNotificationDetails) *NotificationSchemeEventDetails {
	this := NotificationSchemeEventDetails{}
	this.Event = event
	this.Notifications = notifications
	return &this
}

// NewNotificationSchemeEventDetailsWithDefaults instantiates a new NotificationSchemeEventDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationSchemeEventDetailsWithDefaults() *NotificationSchemeEventDetails {
	this := NotificationSchemeEventDetails{}
	return &this
}

// GetEvent returns the Event field value
func (o *NotificationSchemeEventDetails) GetEvent() NotificationSchemeEventTypeId {
	if o == nil {
		var ret NotificationSchemeEventTypeId
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *NotificationSchemeEventDetails) GetEventOk() (*NotificationSchemeEventTypeId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *NotificationSchemeEventDetails) SetEvent(v NotificationSchemeEventTypeId) {
	o.Event = v
}

// GetNotifications returns the Notifications field value
func (o *NotificationSchemeEventDetails) GetNotifications() []NotificationSchemeNotificationDetails {
	if o == nil {
		var ret []NotificationSchemeNotificationDetails
		return ret
	}

	return o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value
// and a boolean to check if the value has been set.
func (o *NotificationSchemeEventDetails) GetNotificationsOk() ([]NotificationSchemeNotificationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notifications, true
}

// SetNotifications sets field value
func (o *NotificationSchemeEventDetails) SetNotifications(v []NotificationSchemeNotificationDetails) {
	o.Notifications = v
}

func (o NotificationSchemeEventDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationSchemeEventDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["notifications"] = o.Notifications

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationSchemeEventDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"notifications",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotificationSchemeEventDetails := _NotificationSchemeEventDetails{}

	err = json.Unmarshal(data, &varNotificationSchemeEventDetails)

	if err != nil {
		return err
	}

	*o = NotificationSchemeEventDetails(varNotificationSchemeEventDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "notifications")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationSchemeEventDetails struct {
	value *NotificationSchemeEventDetails
	isSet bool
}

func (v NullableNotificationSchemeEventDetails) Get() *NotificationSchemeEventDetails {
	return v.value
}

func (v *NullableNotificationSchemeEventDetails) Set(val *NotificationSchemeEventDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationSchemeEventDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationSchemeEventDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationSchemeEventDetails(val *NotificationSchemeEventDetails) *NullableNotificationSchemeEventDetails {
	return &NullableNotificationSchemeEventDetails{value: val, isSet: true}
}

func (v NullableNotificationSchemeEventDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationSchemeEventDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


