/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The wrapper for the issue creation metadata for a list of projects.
type IssueCreateMetadata struct {
	// Expand options that include additional project details in the response.
	Expand string `json:"expand,omitempty"`
	// List of projects and their issue creation metadata.
	Projects []ProjectIssueCreateMetadata `json:"projects,omitempty"`
}
