/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the CustomFieldReplacement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldReplacement{}

// CustomFieldReplacement Details about the replacement for a deleted version.
type CustomFieldReplacement struct {
	// The ID of the custom field in which to replace the version number.
	CustomFieldId *int64 `json:"customFieldId,omitempty"`
	// The version number to use as a replacement for the deleted version.
	MoveTo *int64 `json:"moveTo,omitempty"`
}

// NewCustomFieldReplacement instantiates a new CustomFieldReplacement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldReplacement() *CustomFieldReplacement {
	this := CustomFieldReplacement{}
	return &this
}

// NewCustomFieldReplacementWithDefaults instantiates a new CustomFieldReplacement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldReplacementWithDefaults() *CustomFieldReplacement {
	this := CustomFieldReplacement{}
	return &this
}

// GetCustomFieldId returns the CustomFieldId field value if set, zero value otherwise.
func (o *CustomFieldReplacement) GetCustomFieldId() int64 {
	if o == nil || IsNil(o.CustomFieldId) {
		var ret int64
		return ret
	}
	return *o.CustomFieldId
}

// GetCustomFieldIdOk returns a tuple with the CustomFieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldReplacement) GetCustomFieldIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CustomFieldId) {
		return nil, false
	}
	return o.CustomFieldId, true
}

// HasCustomFieldId returns a boolean if a field has been set.
func (o *CustomFieldReplacement) HasCustomFieldId() bool {
	if o != nil && !IsNil(o.CustomFieldId) {
		return true
	}

	return false
}

// SetCustomFieldId gets a reference to the given int64 and assigns it to the CustomFieldId field.
func (o *CustomFieldReplacement) SetCustomFieldId(v int64) {
	o.CustomFieldId = &v
}

// GetMoveTo returns the MoveTo field value if set, zero value otherwise.
func (o *CustomFieldReplacement) GetMoveTo() int64 {
	if o == nil || IsNil(o.MoveTo) {
		var ret int64
		return ret
	}
	return *o.MoveTo
}

// GetMoveToOk returns a tuple with the MoveTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldReplacement) GetMoveToOk() (*int64, bool) {
	if o == nil || IsNil(o.MoveTo) {
		return nil, false
	}
	return o.MoveTo, true
}

// HasMoveTo returns a boolean if a field has been set.
func (o *CustomFieldReplacement) HasMoveTo() bool {
	if o != nil && !IsNil(o.MoveTo) {
		return true
	}

	return false
}

// SetMoveTo gets a reference to the given int64 and assigns it to the MoveTo field.
func (o *CustomFieldReplacement) SetMoveTo(v int64) {
	o.MoveTo = &v
}

func (o CustomFieldReplacement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldReplacement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomFieldId) {
		toSerialize["customFieldId"] = o.CustomFieldId
	}
	if !IsNil(o.MoveTo) {
		toSerialize["moveTo"] = o.MoveTo
	}
	return toSerialize, nil
}

type NullableCustomFieldReplacement struct {
	value *CustomFieldReplacement
	isSet bool
}

func (v NullableCustomFieldReplacement) Get() *CustomFieldReplacement {
	return v.value
}

func (v *NullableCustomFieldReplacement) Set(val *CustomFieldReplacement) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldReplacement) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldReplacement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldReplacement(val *CustomFieldReplacement) *NullableCustomFieldReplacement {
	return &NullableCustomFieldReplacement{value: val, isSet: true}
}

func (v NullableCustomFieldReplacement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldReplacement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


