/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JiraMultiSelectComponentField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JiraMultiSelectComponentField{}

// JiraMultiSelectComponentField struct for JiraMultiSelectComponentField
type JiraMultiSelectComponentField struct {
	BulkEditMultiSelectFieldOption string `json:"bulkEditMultiSelectFieldOption"`
	Components []JiraComponentField `json:"components"`
	FieldId string `json:"fieldId"`
}

type _JiraMultiSelectComponentField JiraMultiSelectComponentField

// NewJiraMultiSelectComponentField instantiates a new JiraMultiSelectComponentField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJiraMultiSelectComponentField(bulkEditMultiSelectFieldOption string, components []JiraComponentField, fieldId string) *JiraMultiSelectComponentField {
	this := JiraMultiSelectComponentField{}
	this.BulkEditMultiSelectFieldOption = bulkEditMultiSelectFieldOption
	this.Components = components
	this.FieldId = fieldId
	return &this
}

// NewJiraMultiSelectComponentFieldWithDefaults instantiates a new JiraMultiSelectComponentField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJiraMultiSelectComponentFieldWithDefaults() *JiraMultiSelectComponentField {
	this := JiraMultiSelectComponentField{}
	return &this
}

// GetBulkEditMultiSelectFieldOption returns the BulkEditMultiSelectFieldOption field value
func (o *JiraMultiSelectComponentField) GetBulkEditMultiSelectFieldOption() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BulkEditMultiSelectFieldOption
}

// GetBulkEditMultiSelectFieldOptionOk returns a tuple with the BulkEditMultiSelectFieldOption field value
// and a boolean to check if the value has been set.
func (o *JiraMultiSelectComponentField) GetBulkEditMultiSelectFieldOptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BulkEditMultiSelectFieldOption, true
}

// SetBulkEditMultiSelectFieldOption sets field value
func (o *JiraMultiSelectComponentField) SetBulkEditMultiSelectFieldOption(v string) {
	o.BulkEditMultiSelectFieldOption = v
}

// GetComponents returns the Components field value
func (o *JiraMultiSelectComponentField) GetComponents() []JiraComponentField {
	if o == nil {
		var ret []JiraComponentField
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *JiraMultiSelectComponentField) GetComponentsOk() ([]JiraComponentField, bool) {
	if o == nil {
		return nil, false
	}
	return o.Components, true
}

// SetComponents sets field value
func (o *JiraMultiSelectComponentField) SetComponents(v []JiraComponentField) {
	o.Components = v
}

// GetFieldId returns the FieldId field value
func (o *JiraMultiSelectComponentField) GetFieldId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value
// and a boolean to check if the value has been set.
func (o *JiraMultiSelectComponentField) GetFieldIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldId, true
}

// SetFieldId sets field value
func (o *JiraMultiSelectComponentField) SetFieldId(v string) {
	o.FieldId = v
}

func (o JiraMultiSelectComponentField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JiraMultiSelectComponentField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bulkEditMultiSelectFieldOption"] = o.BulkEditMultiSelectFieldOption
	toSerialize["components"] = o.Components
	toSerialize["fieldId"] = o.FieldId
	return toSerialize, nil
}

func (o *JiraMultiSelectComponentField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bulkEditMultiSelectFieldOption",
		"components",
		"fieldId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJiraMultiSelectComponentField := _JiraMultiSelectComponentField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJiraMultiSelectComponentField)

	if err != nil {
		return err
	}

	*o = JiraMultiSelectComponentField(varJiraMultiSelectComponentField)

	return err
}

type NullableJiraMultiSelectComponentField struct {
	value *JiraMultiSelectComponentField
	isSet bool
}

func (v NullableJiraMultiSelectComponentField) Get() *JiraMultiSelectComponentField {
	return v.value
}

func (v *NullableJiraMultiSelectComponentField) Set(val *JiraMultiSelectComponentField) {
	v.value = val
	v.isSet = true
}

func (v NullableJiraMultiSelectComponentField) IsSet() bool {
	return v.isSet
}

func (v *NullableJiraMultiSelectComponentField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJiraMultiSelectComponentField(val *JiraMultiSelectComponentField) *NullableJiraMultiSelectComponentField {
	return &NullableJiraMultiSelectComponentField{value: val, isSet: true}
}

func (v NullableJiraMultiSelectComponentField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJiraMultiSelectComponentField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


