/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScreenDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScreenDetails{}

// ScreenDetails Details of a screen.
type ScreenDetails struct {
	// The description of the screen. The maximum length is 255 characters.
	Description *string `json:"description,omitempty"`
	// The name of the screen. The name must be unique. The maximum length is 255 characters.
	Name string `json:"name"`
}

type _ScreenDetails ScreenDetails

// NewScreenDetails instantiates a new ScreenDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenDetails(name string) *ScreenDetails {
	this := ScreenDetails{}
	this.Name = name
	return &this
}

// NewScreenDetailsWithDefaults instantiates a new ScreenDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenDetailsWithDefaults() *ScreenDetails {
	this := ScreenDetails{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScreenDetails) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenDetails) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScreenDetails) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScreenDetails) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *ScreenDetails) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScreenDetails) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScreenDetails) SetName(v string) {
	o.Name = v
}

func (o ScreenDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScreenDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ScreenDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScreenDetails := _ScreenDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScreenDetails)

	if err != nil {
		return err
	}

	*o = ScreenDetails(varScreenDetails)

	return err
}

type NullableScreenDetails struct {
	value *ScreenDetails
	isSet bool
}

func (v NullableScreenDetails) Get() *ScreenDetails {
	return v.value
}

func (v *NullableScreenDetails) Set(val *ScreenDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenDetails(val *ScreenDetails) *NullableScreenDetails {
	return &NullableScreenDetails{value: val, isSet: true}
}

func (v NullableScreenDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


