/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JiraSingleLineTextField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JiraSingleLineTextField{}

// JiraSingleLineTextField struct for JiraSingleLineTextField
type JiraSingleLineTextField struct {
	FieldId string `json:"fieldId"`
	Text string `json:"text"`
}

type _JiraSingleLineTextField JiraSingleLineTextField

// NewJiraSingleLineTextField instantiates a new JiraSingleLineTextField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJiraSingleLineTextField(fieldId string, text string) *JiraSingleLineTextField {
	this := JiraSingleLineTextField{}
	this.FieldId = fieldId
	this.Text = text
	return &this
}

// NewJiraSingleLineTextFieldWithDefaults instantiates a new JiraSingleLineTextField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJiraSingleLineTextFieldWithDefaults() *JiraSingleLineTextField {
	this := JiraSingleLineTextField{}
	return &this
}

// GetFieldId returns the FieldId field value
func (o *JiraSingleLineTextField) GetFieldId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value
// and a boolean to check if the value has been set.
func (o *JiraSingleLineTextField) GetFieldIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldId, true
}

// SetFieldId sets field value
func (o *JiraSingleLineTextField) SetFieldId(v string) {
	o.FieldId = v
}

// GetText returns the Text field value
func (o *JiraSingleLineTextField) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *JiraSingleLineTextField) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *JiraSingleLineTextField) SetText(v string) {
	o.Text = v
}

func (o JiraSingleLineTextField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JiraSingleLineTextField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fieldId"] = o.FieldId
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *JiraSingleLineTextField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fieldId",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJiraSingleLineTextField := _JiraSingleLineTextField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJiraSingleLineTextField)

	if err != nil {
		return err
	}

	*o = JiraSingleLineTextField(varJiraSingleLineTextField)

	return err
}

type NullableJiraSingleLineTextField struct {
	value *JiraSingleLineTextField
	isSet bool
}

func (v NullableJiraSingleLineTextField) Get() *JiraSingleLineTextField {
	return v.value
}

func (v *NullableJiraSingleLineTextField) Set(val *JiraSingleLineTextField) {
	v.value = val
	v.isSet = true
}

func (v NullableJiraSingleLineTextField) IsSet() bool {
	return v.isSet
}

func (v *NullableJiraSingleLineTextField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJiraSingleLineTextField(val *JiraSingleLineTextField) *NullableJiraSingleLineTextField {
	return &NullableJiraSingleLineTextField{value: val, isSet: true}
}

func (v NullableJiraSingleLineTextField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJiraSingleLineTextField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


