/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the IssueLayoutPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssueLayoutPayload{}

// IssueLayoutPayload Defines the payload to configure the issue layouts for a project.
type IssueLayoutPayload struct {
	ContainerId *ProjectCreateResourceIdentifier `json:"containerId,omitempty"`
	// The issue layout type
	IssueLayoutType *string `json:"issueLayoutType,omitempty"`
	// The configuration of items in the issue layout
	Items []IssueLayoutItemPayload `json:"items,omitempty"`
	Pcri *ProjectCreateResourceIdentifier `json:"pcri,omitempty"`
}

// NewIssueLayoutPayload instantiates a new IssueLayoutPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssueLayoutPayload() *IssueLayoutPayload {
	this := IssueLayoutPayload{}
	return &this
}

// NewIssueLayoutPayloadWithDefaults instantiates a new IssueLayoutPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssueLayoutPayloadWithDefaults() *IssueLayoutPayload {
	this := IssueLayoutPayload{}
	return &this
}

// GetContainerId returns the ContainerId field value if set, zero value otherwise.
func (o *IssueLayoutPayload) GetContainerId() ProjectCreateResourceIdentifier {
	if o == nil || IsNil(o.ContainerId) {
		var ret ProjectCreateResourceIdentifier
		return ret
	}
	return *o.ContainerId
}

// GetContainerIdOk returns a tuple with the ContainerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueLayoutPayload) GetContainerIdOk() (*ProjectCreateResourceIdentifier, bool) {
	if o == nil || IsNil(o.ContainerId) {
		return nil, false
	}
	return o.ContainerId, true
}

// HasContainerId returns a boolean if a field has been set.
func (o *IssueLayoutPayload) HasContainerId() bool {
	if o != nil && !IsNil(o.ContainerId) {
		return true
	}

	return false
}

// SetContainerId gets a reference to the given ProjectCreateResourceIdentifier and assigns it to the ContainerId field.
func (o *IssueLayoutPayload) SetContainerId(v ProjectCreateResourceIdentifier) {
	o.ContainerId = &v
}

// GetIssueLayoutType returns the IssueLayoutType field value if set, zero value otherwise.
func (o *IssueLayoutPayload) GetIssueLayoutType() string {
	if o == nil || IsNil(o.IssueLayoutType) {
		var ret string
		return ret
	}
	return *o.IssueLayoutType
}

// GetIssueLayoutTypeOk returns a tuple with the IssueLayoutType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueLayoutPayload) GetIssueLayoutTypeOk() (*string, bool) {
	if o == nil || IsNil(o.IssueLayoutType) {
		return nil, false
	}
	return o.IssueLayoutType, true
}

// HasIssueLayoutType returns a boolean if a field has been set.
func (o *IssueLayoutPayload) HasIssueLayoutType() bool {
	if o != nil && !IsNil(o.IssueLayoutType) {
		return true
	}

	return false
}

// SetIssueLayoutType gets a reference to the given string and assigns it to the IssueLayoutType field.
func (o *IssueLayoutPayload) SetIssueLayoutType(v string) {
	o.IssueLayoutType = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *IssueLayoutPayload) GetItems() []IssueLayoutItemPayload {
	if o == nil || IsNil(o.Items) {
		var ret []IssueLayoutItemPayload
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueLayoutPayload) GetItemsOk() ([]IssueLayoutItemPayload, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *IssueLayoutPayload) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []IssueLayoutItemPayload and assigns it to the Items field.
func (o *IssueLayoutPayload) SetItems(v []IssueLayoutItemPayload) {
	o.Items = v
}

// GetPcri returns the Pcri field value if set, zero value otherwise.
func (o *IssueLayoutPayload) GetPcri() ProjectCreateResourceIdentifier {
	if o == nil || IsNil(o.Pcri) {
		var ret ProjectCreateResourceIdentifier
		return ret
	}
	return *o.Pcri
}

// GetPcriOk returns a tuple with the Pcri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssueLayoutPayload) GetPcriOk() (*ProjectCreateResourceIdentifier, bool) {
	if o == nil || IsNil(o.Pcri) {
		return nil, false
	}
	return o.Pcri, true
}

// HasPcri returns a boolean if a field has been set.
func (o *IssueLayoutPayload) HasPcri() bool {
	if o != nil && !IsNil(o.Pcri) {
		return true
	}

	return false
}

// SetPcri gets a reference to the given ProjectCreateResourceIdentifier and assigns it to the Pcri field.
func (o *IssueLayoutPayload) SetPcri(v ProjectCreateResourceIdentifier) {
	o.Pcri = &v
}

func (o IssueLayoutPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssueLayoutPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContainerId) {
		toSerialize["containerId"] = o.ContainerId
	}
	if !IsNil(o.IssueLayoutType) {
		toSerialize["issueLayoutType"] = o.IssueLayoutType
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Pcri) {
		toSerialize["pcri"] = o.Pcri
	}
	return toSerialize, nil
}

type NullableIssueLayoutPayload struct {
	value *IssueLayoutPayload
	isSet bool
}

func (v NullableIssueLayoutPayload) Get() *IssueLayoutPayload {
	return v.value
}

func (v *NullableIssueLayoutPayload) Set(val *IssueLayoutPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIssueLayoutPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIssueLayoutPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssueLayoutPayload(val *IssueLayoutPayload) *NullableIssueLayoutPayload {
	return &NullableIssueLayoutPayload{value: val, isSet: true}
}

func (v NullableIssueLayoutPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssueLayoutPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


