/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the JiraExpressionEvaluateContextBean type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JiraExpressionEvaluateContextBean{}

// JiraExpressionEvaluateContextBean struct for JiraExpressionEvaluateContextBean
type JiraExpressionEvaluateContextBean struct {
	// The ID of the board that is available under the `board` variable when evaluating the expression.
	Board *int64 `json:"board,omitempty"`
	// Custom context variables and their types. These variable types are available for use in a custom context:   *  `user`: A [user](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#user) specified as an Atlassian account ID.  *  `issue`: An [issue](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#issue) specified by ID or key. All the fields of the issue object are available in the Jira expression.  *  `json`: A JSON object containing custom content.  *  `list`: A JSON list of `user`, `issue`, or `json` variable types.
	Custom []CustomContextVariable `json:"custom,omitempty"`
	// The ID of the customer request that is available under the `customerRequest` variable when evaluating the expression. This is the same as the ID of the underlying Jira issue, but the customer request context variable will have a different type.
	CustomerRequest *int64 `json:"customerRequest,omitempty"`
	// The issue that is available under the `issue` variable when evaluating the expression.
	Issue *IdOrKeyBean `json:"issue,omitempty"`
	// The collection of issues that is available under the `issues` variable when evaluating the expression.
	Issues *JexpEvaluateCtxIssues `json:"issues,omitempty"`
	// The project that is available under the `project` variable when evaluating the expression.
	Project *IdOrKeyBean `json:"project,omitempty"`
	// The ID of the service desk that is available under the `serviceDesk` variable when evaluating the expression.
	ServiceDesk *int64 `json:"serviceDesk,omitempty"`
	// The ID of the sprint that is available under the `sprint` variable when evaluating the expression.
	Sprint *int64 `json:"sprint,omitempty"`
}

// NewJiraExpressionEvaluateContextBean instantiates a new JiraExpressionEvaluateContextBean object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJiraExpressionEvaluateContextBean() *JiraExpressionEvaluateContextBean {
	this := JiraExpressionEvaluateContextBean{}
	return &this
}

// NewJiraExpressionEvaluateContextBeanWithDefaults instantiates a new JiraExpressionEvaluateContextBean object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJiraExpressionEvaluateContextBeanWithDefaults() *JiraExpressionEvaluateContextBean {
	this := JiraExpressionEvaluateContextBean{}
	return &this
}

// GetBoard returns the Board field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetBoard() int64 {
	if o == nil || IsNil(o.Board) {
		var ret int64
		return ret
	}
	return *o.Board
}

// GetBoardOk returns a tuple with the Board field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetBoardOk() (*int64, bool) {
	if o == nil || IsNil(o.Board) {
		return nil, false
	}
	return o.Board, true
}

// HasBoard returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasBoard() bool {
	if o != nil && !IsNil(o.Board) {
		return true
	}

	return false
}

// SetBoard gets a reference to the given int64 and assigns it to the Board field.
func (o *JiraExpressionEvaluateContextBean) SetBoard(v int64) {
	o.Board = &v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetCustom() []CustomContextVariable {
	if o == nil || IsNil(o.Custom) {
		var ret []CustomContextVariable
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetCustomOk() ([]CustomContextVariable, bool) {
	if o == nil || IsNil(o.Custom) {
		return nil, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given []CustomContextVariable and assigns it to the Custom field.
func (o *JiraExpressionEvaluateContextBean) SetCustom(v []CustomContextVariable) {
	o.Custom = v
}

// GetCustomerRequest returns the CustomerRequest field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetCustomerRequest() int64 {
	if o == nil || IsNil(o.CustomerRequest) {
		var ret int64
		return ret
	}
	return *o.CustomerRequest
}

// GetCustomerRequestOk returns a tuple with the CustomerRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetCustomerRequestOk() (*int64, bool) {
	if o == nil || IsNil(o.CustomerRequest) {
		return nil, false
	}
	return o.CustomerRequest, true
}

// HasCustomerRequest returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasCustomerRequest() bool {
	if o != nil && !IsNil(o.CustomerRequest) {
		return true
	}

	return false
}

// SetCustomerRequest gets a reference to the given int64 and assigns it to the CustomerRequest field.
func (o *JiraExpressionEvaluateContextBean) SetCustomerRequest(v int64) {
	o.CustomerRequest = &v
}

// GetIssue returns the Issue field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetIssue() IdOrKeyBean {
	if o == nil || IsNil(o.Issue) {
		var ret IdOrKeyBean
		return ret
	}
	return *o.Issue
}

// GetIssueOk returns a tuple with the Issue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetIssueOk() (*IdOrKeyBean, bool) {
	if o == nil || IsNil(o.Issue) {
		return nil, false
	}
	return o.Issue, true
}

// HasIssue returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasIssue() bool {
	if o != nil && !IsNil(o.Issue) {
		return true
	}

	return false
}

// SetIssue gets a reference to the given IdOrKeyBean and assigns it to the Issue field.
func (o *JiraExpressionEvaluateContextBean) SetIssue(v IdOrKeyBean) {
	o.Issue = &v
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetIssues() JexpEvaluateCtxIssues {
	if o == nil || IsNil(o.Issues) {
		var ret JexpEvaluateCtxIssues
		return ret
	}
	return *o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetIssuesOk() (*JexpEvaluateCtxIssues, bool) {
	if o == nil || IsNil(o.Issues) {
		return nil, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given JexpEvaluateCtxIssues and assigns it to the Issues field.
func (o *JiraExpressionEvaluateContextBean) SetIssues(v JexpEvaluateCtxIssues) {
	o.Issues = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetProject() IdOrKeyBean {
	if o == nil || IsNil(o.Project) {
		var ret IdOrKeyBean
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetProjectOk() (*IdOrKeyBean, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given IdOrKeyBean and assigns it to the Project field.
func (o *JiraExpressionEvaluateContextBean) SetProject(v IdOrKeyBean) {
	o.Project = &v
}

// GetServiceDesk returns the ServiceDesk field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetServiceDesk() int64 {
	if o == nil || IsNil(o.ServiceDesk) {
		var ret int64
		return ret
	}
	return *o.ServiceDesk
}

// GetServiceDeskOk returns a tuple with the ServiceDesk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetServiceDeskOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceDesk) {
		return nil, false
	}
	return o.ServiceDesk, true
}

// HasServiceDesk returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasServiceDesk() bool {
	if o != nil && !IsNil(o.ServiceDesk) {
		return true
	}

	return false
}

// SetServiceDesk gets a reference to the given int64 and assigns it to the ServiceDesk field.
func (o *JiraExpressionEvaluateContextBean) SetServiceDesk(v int64) {
	o.ServiceDesk = &v
}

// GetSprint returns the Sprint field value if set, zero value otherwise.
func (o *JiraExpressionEvaluateContextBean) GetSprint() int64 {
	if o == nil || IsNil(o.Sprint) {
		var ret int64
		return ret
	}
	return *o.Sprint
}

// GetSprintOk returns a tuple with the Sprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JiraExpressionEvaluateContextBean) GetSprintOk() (*int64, bool) {
	if o == nil || IsNil(o.Sprint) {
		return nil, false
	}
	return o.Sprint, true
}

// HasSprint returns a boolean if a field has been set.
func (o *JiraExpressionEvaluateContextBean) HasSprint() bool {
	if o != nil && !IsNil(o.Sprint) {
		return true
	}

	return false
}

// SetSprint gets a reference to the given int64 and assigns it to the Sprint field.
func (o *JiraExpressionEvaluateContextBean) SetSprint(v int64) {
	o.Sprint = &v
}

func (o JiraExpressionEvaluateContextBean) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JiraExpressionEvaluateContextBean) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Board) {
		toSerialize["board"] = o.Board
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.CustomerRequest) {
		toSerialize["customerRequest"] = o.CustomerRequest
	}
	if !IsNil(o.Issue) {
		toSerialize["issue"] = o.Issue
	}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.ServiceDesk) {
		toSerialize["serviceDesk"] = o.ServiceDesk
	}
	if !IsNil(o.Sprint) {
		toSerialize["sprint"] = o.Sprint
	}
	return toSerialize, nil
}

type NullableJiraExpressionEvaluateContextBean struct {
	value *JiraExpressionEvaluateContextBean
	isSet bool
}

func (v NullableJiraExpressionEvaluateContextBean) Get() *JiraExpressionEvaluateContextBean {
	return v.value
}

func (v *NullableJiraExpressionEvaluateContextBean) Set(val *JiraExpressionEvaluateContextBean) {
	v.value = val
	v.isSet = true
}

func (v NullableJiraExpressionEvaluateContextBean) IsSet() bool {
	return v.isSet
}

func (v *NullableJiraExpressionEvaluateContextBean) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJiraExpressionEvaluateContextBean(val *JiraExpressionEvaluateContextBean) *NullableJiraExpressionEvaluateContextBean {
	return &NullableJiraExpressionEvaluateContextBean{value: val, isSet: true}
}

func (v NullableJiraExpressionEvaluateContextBean) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJiraExpressionEvaluateContextBean) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


