/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the SecurityScheme type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecurityScheme{}

// SecurityScheme Details about a security scheme.
type SecurityScheme struct {
	// The ID of the default security level.
	DefaultSecurityLevelId *int64 `json:"defaultSecurityLevelId,omitempty"`
	// The description of the issue security scheme.
	Description *string `json:"description,omitempty"`
	// The ID of the issue security scheme.
	Id *int64 `json:"id,omitempty"`
	Levels []SecurityLevel `json:"levels,omitempty"`
	// The name of the issue security scheme.
	Name *string `json:"name,omitempty"`
	// The URL of the issue security scheme.
	Self *string `json:"self,omitempty"`
}

// NewSecurityScheme instantiates a new SecurityScheme object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecurityScheme() *SecurityScheme {
	this := SecurityScheme{}
	return &this
}

// NewSecuritySchemeWithDefaults instantiates a new SecurityScheme object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecuritySchemeWithDefaults() *SecurityScheme {
	this := SecurityScheme{}
	return &this
}

// GetDefaultSecurityLevelId returns the DefaultSecurityLevelId field value if set, zero value otherwise.
func (o *SecurityScheme) GetDefaultSecurityLevelId() int64 {
	if o == nil || IsNil(o.DefaultSecurityLevelId) {
		var ret int64
		return ret
	}
	return *o.DefaultSecurityLevelId
}

// GetDefaultSecurityLevelIdOk returns a tuple with the DefaultSecurityLevelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetDefaultSecurityLevelIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DefaultSecurityLevelId) {
		return nil, false
	}
	return o.DefaultSecurityLevelId, true
}

// HasDefaultSecurityLevelId returns a boolean if a field has been set.
func (o *SecurityScheme) HasDefaultSecurityLevelId() bool {
	if o != nil && !IsNil(o.DefaultSecurityLevelId) {
		return true
	}

	return false
}

// SetDefaultSecurityLevelId gets a reference to the given int64 and assigns it to the DefaultSecurityLevelId field.
func (o *SecurityScheme) SetDefaultSecurityLevelId(v int64) {
	o.DefaultSecurityLevelId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SecurityScheme) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SecurityScheme) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SecurityScheme) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SecurityScheme) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SecurityScheme) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *SecurityScheme) SetId(v int64) {
	o.Id = &v
}

// GetLevels returns the Levels field value if set, zero value otherwise.
func (o *SecurityScheme) GetLevels() []SecurityLevel {
	if o == nil || IsNil(o.Levels) {
		var ret []SecurityLevel
		return ret
	}
	return o.Levels
}

// GetLevelsOk returns a tuple with the Levels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetLevelsOk() ([]SecurityLevel, bool) {
	if o == nil || IsNil(o.Levels) {
		return nil, false
	}
	return o.Levels, true
}

// HasLevels returns a boolean if a field has been set.
func (o *SecurityScheme) HasLevels() bool {
	if o != nil && !IsNil(o.Levels) {
		return true
	}

	return false
}

// SetLevels gets a reference to the given []SecurityLevel and assigns it to the Levels field.
func (o *SecurityScheme) SetLevels(v []SecurityLevel) {
	o.Levels = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SecurityScheme) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SecurityScheme) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SecurityScheme) SetName(v string) {
	o.Name = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *SecurityScheme) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecurityScheme) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *SecurityScheme) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *SecurityScheme) SetSelf(v string) {
	o.Self = &v
}

func (o SecurityScheme) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecurityScheme) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefaultSecurityLevelId) {
		toSerialize["defaultSecurityLevelId"] = o.DefaultSecurityLevelId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Levels) {
		toSerialize["levels"] = o.Levels
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableSecurityScheme struct {
	value *SecurityScheme
	isSet bool
}

func (v NullableSecurityScheme) Get() *SecurityScheme {
	return v.value
}

func (v *NullableSecurityScheme) Set(val *SecurityScheme) {
	v.value = val
	v.isSet = true
}

func (v NullableSecurityScheme) IsSet() bool {
	return v.isSet
}

func (v *NullableSecurityScheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecurityScheme(val *SecurityScheme) *NullableSecurityScheme {
	return &NullableSecurityScheme{value: val, isSet: true}
}

func (v NullableSecurityScheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecurityScheme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


