/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A clause that asserts a previous value of a field. For example, `status WAS \"Resolved\" BY currentUser() BEFORE \"2019/02/02\"`. See [WAS](https://confluence.atlassian.com/x/dgiiLQ#Advancedsearching-operatorsreference-WASWAS) for more information about the WAS operator.
type FieldWasClause struct {
	Field *JqlQueryField `json:"field"`
	Operand *JqlQueryClauseOperand `json:"operand"`
	// The operator between the field and operand.
	Operator string `json:"operator"`
	// The list of time predicates.
	Predicates []JqlQueryClauseTimePredicate `json:"predicates"`
}
