/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the CardLayoutField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardLayoutField{}

// CardLayoutField Card layout settings of the board
type CardLayoutField struct {
	FieldId *string `json:"fieldId,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Position *int32 `json:"position,omitempty"`
}

// NewCardLayoutField instantiates a new CardLayoutField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardLayoutField() *CardLayoutField {
	this := CardLayoutField{}
	return &this
}

// NewCardLayoutFieldWithDefaults instantiates a new CardLayoutField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardLayoutFieldWithDefaults() *CardLayoutField {
	this := CardLayoutField{}
	return &this
}

// GetFieldId returns the FieldId field value if set, zero value otherwise.
func (o *CardLayoutField) GetFieldId() string {
	if o == nil || IsNil(o.FieldId) {
		var ret string
		return ret
	}
	return *o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardLayoutField) GetFieldIdOk() (*string, bool) {
	if o == nil || IsNil(o.FieldId) {
		return nil, false
	}
	return o.FieldId, true
}

// HasFieldId returns a boolean if a field has been set.
func (o *CardLayoutField) HasFieldId() bool {
	if o != nil && !IsNil(o.FieldId) {
		return true
	}

	return false
}

// SetFieldId gets a reference to the given string and assigns it to the FieldId field.
func (o *CardLayoutField) SetFieldId(v string) {
	o.FieldId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CardLayoutField) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardLayoutField) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CardLayoutField) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *CardLayoutField) SetId(v int64) {
	o.Id = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *CardLayoutField) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardLayoutField) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *CardLayoutField) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *CardLayoutField) SetMode(v string) {
	o.Mode = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *CardLayoutField) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardLayoutField) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *CardLayoutField) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *CardLayoutField) SetPosition(v int32) {
	o.Position = &v
}

func (o CardLayoutField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardLayoutField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldId) {
		toSerialize["fieldId"] = o.FieldId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	return toSerialize, nil
}

type NullableCardLayoutField struct {
	value *CardLayoutField
	isSet bool
}

func (v NullableCardLayoutField) Get() *CardLayoutField {
	return v.value
}

func (v *NullableCardLayoutField) Set(val *CardLayoutField) {
	v.value = val
	v.isSet = true
}

func (v NullableCardLayoutField) IsSet() bool {
	return v.isSet
}

func (v *NullableCardLayoutField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardLayoutField(val *CardLayoutField) *NullableCardLayoutField {
	return &NullableCardLayoutField{value: val, isSet: true}
}

func (v NullableCardLayoutField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardLayoutField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


