/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * API version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details of a context to project association.
type CustomFieldContextProjectMapping struct {
	// The ID of the context.
	ContextId string `json:"contextId"`
	// Whether context is global.
	IsGlobalContext bool `json:"isGlobalContext,omitempty"`
	// The ID of the project.
	ProjectId string `json:"projectId,omitempty"`
}
