/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkflowTransition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowTransition{}

// WorkflowTransition A workflow transition.
type WorkflowTransition struct {
	// The transition ID.
	Id int32 `json:"id"`
	// The transition name.
	Name string `json:"name"`
}

type _WorkflowTransition WorkflowTransition

// NewWorkflowTransition instantiates a new WorkflowTransition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowTransition(id int32, name string) *WorkflowTransition {
	this := WorkflowTransition{}
	this.Id = id
	this.Name = name
	return &this
}

// NewWorkflowTransitionWithDefaults instantiates a new WorkflowTransition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowTransitionWithDefaults() *WorkflowTransition {
	this := WorkflowTransition{}
	return &this
}

// GetId returns the Id field value
func (o *WorkflowTransition) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowTransition) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowTransition) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *WorkflowTransition) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowTransition) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowTransition) SetName(v string) {
	o.Name = v
}

func (o WorkflowTransition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowTransition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *WorkflowTransition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowTransition := _WorkflowTransition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowTransition)

	if err != nil {
		return err
	}

	*o = WorkflowTransition(varWorkflowTransition)

	return err
}

type NullableWorkflowTransition struct {
	value *WorkflowTransition
	isSet bool
}

func (v NullableWorkflowTransition) Get() *WorkflowTransition {
	return v.value
}

func (v *NullableWorkflowTransition) Set(val *WorkflowTransition) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowTransition) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowTransition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowTransition(val *WorkflowTransition) *NullableWorkflowTransition {
	return &NullableWorkflowTransition{value: val, isSet: true}
}

func (v NullableWorkflowTransition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowTransition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


