/*
The Jira Cloud platform REST API

Jira Cloud platform REST API documentation

API version: 1001.0.0-SNAPSHOT-e4f05783a723054bc221d0780e48a2dc2ed25997
Contact: ecosystem@atlassian.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the InputStreamSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputStreamSource{}

// InputStreamSource struct for InputStreamSource
type InputStreamSource struct {
	InputStream map[string]interface{} `json:"inputStream,omitempty"`
}

// NewInputStreamSource instantiates a new InputStreamSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputStreamSource() *InputStreamSource {
	this := InputStreamSource{}
	return &this
}

// NewInputStreamSourceWithDefaults instantiates a new InputStreamSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputStreamSourceWithDefaults() *InputStreamSource {
	this := InputStreamSource{}
	return &this
}

// GetInputStream returns the InputStream field value if set, zero value otherwise.
func (o *InputStreamSource) GetInputStream() map[string]interface{} {
	if o == nil || IsNil(o.InputStream) {
		var ret map[string]interface{}
		return ret
	}
	return o.InputStream
}

// GetInputStreamOk returns a tuple with the InputStream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputStreamSource) GetInputStreamOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InputStream) {
		return map[string]interface{}{}, false
	}
	return o.InputStream, true
}

// HasInputStream returns a boolean if a field has been set.
func (o *InputStreamSource) HasInputStream() bool {
	if o != nil && !IsNil(o.InputStream) {
		return true
	}

	return false
}

// SetInputStream gets a reference to the given map[string]interface{} and assigns it to the InputStream field.
func (o *InputStreamSource) SetInputStream(v map[string]interface{}) {
	o.InputStream = v
}

func (o InputStreamSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputStreamSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InputStream) {
		toSerialize["inputStream"] = o.InputStream
	}
	return toSerialize, nil
}

type NullableInputStreamSource struct {
	value *InputStreamSource
	isSet bool
}

func (v NullableInputStreamSource) Get() *InputStreamSource {
	return v.value
}

func (v *NullableInputStreamSource) Set(val *InputStreamSource) {
	v.value = val
	v.isSet = true
}

func (v NullableInputStreamSource) IsSet() bool {
	return v.isSet
}

func (v *NullableInputStreamSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputStreamSource(val *InputStreamSource) *NullableInputStreamSource {
	return &NullableInputStreamSource{value: val, isSet: true}
}

func (v NullableInputStreamSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputStreamSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


