/*
Jira Software Cloud API

Testing DeploymentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swagger_software

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/alexhokl/jira-cli/swagger_software"
)

func Test_swagger_software_DeploymentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeploymentsAPIService DeleteDeploymentByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pipelineId string
		var environmentId string
		var deploymentSequenceNumber int64

		httpRes, err := apiClient.DeploymentsAPI.DeleteDeploymentByKey(context.Background(), pipelineId, environmentId, deploymentSequenceNumber).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeploymentsAPIService DeleteDeploymentsByProperty", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DeploymentsAPI.DeleteDeploymentsByProperty(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeploymentsAPIService GetDeploymentByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pipelineId string
		var environmentId string
		var deploymentSequenceNumber int64

		resp, httpRes, err := apiClient.DeploymentsAPI.GetDeploymentByKey(context.Background(), pipelineId, environmentId, deploymentSequenceNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeploymentsAPIService GetDeploymentGatingStatusByKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pipelineId string
		var environmentId string
		var deploymentSequenceNumber int64

		resp, httpRes, err := apiClient.DeploymentsAPI.GetDeploymentGatingStatusByKey(context.Background(), pipelineId, environmentId, deploymentSequenceNumber).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DeploymentsAPIService SubmitDeployments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DeploymentsAPI.SubmitDeployments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
