/*
The Jira Cloud platform REST API

Testing ScreenTabsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package swagger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/alexhokl/jira-cli/swagger"
)

func Test_swagger_ScreenTabsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ScreenTabsAPIService AddScreenTab", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var screenId int64

		resp, httpRes, err := apiClient.ScreenTabsAPI.AddScreenTab(context.Background(), screenId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScreenTabsAPIService DeleteScreenTab", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var screenId int64
		var tabId int64

		httpRes, err := apiClient.ScreenTabsAPI.DeleteScreenTab(context.Background(), screenId, tabId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScreenTabsAPIService GetAllScreenTabs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var screenId int64

		resp, httpRes, err := apiClient.ScreenTabsAPI.GetAllScreenTabs(context.Background(), screenId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScreenTabsAPIService GetBulkScreenTabs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ScreenTabsAPI.GetBulkScreenTabs(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScreenTabsAPIService MoveScreenTab", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var screenId int64
		var tabId int64
		var pos int32

		resp, httpRes, err := apiClient.ScreenTabsAPI.MoveScreenTab(context.Background(), screenId, tabId, pos).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScreenTabsAPIService RenameScreenTab", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var screenId int64
		var tabId int64

		resp, httpRes, err := apiClient.ScreenTabsAPI.RenameScreenTab(context.Background(), screenId, tabId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
