/*
Jira Software Cloud API

Jira Software Cloud REST API documentation

API version: 1001.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger_software

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Branch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Branch{}

// Branch Represents a branch in the version control system
type Branch struct {
	// The ID of this entity. Will be used for cross entity linking. Must be unique by entity type within a repository, i.e., only one commit can have ID 'X' in repository 'Y'. But adding, e.g., a branch with ID 'X' to repository 'Y' is acceptable. Only alphanumeric characters, and '~.-_', are allowed. Max length is 1024 characters.
	Id string `json:"id"`
	// List of issues keys that this entity is associated with. They must be valid Jira issue keys.
	// Deprecated
	IssueKeys []string `json:"issueKeys,omitempty"`
	// The Jira issue keys or IDs to associate the branch with.
	Associations []IssueIdOrKeysAssociation `json:"associations,omitempty"`
	// An ID used to apply an ordering to updates for this entity in the case of out-of-order receipt of update requests. This can be any monotonically increasing number. A suggested implementation is to use epoch millis from the provider system, but other alternatives are valid (e.g. a provider could store a counter against each entity and increment that on each update to Jira). Updates for an entity that are received with an updateSqeuenceId lower than what is currently stored will be ignored.
	UpdateSequenceId int64 `json:"updateSequenceId"`
	// The name of the branch. Max length is 512 characters.
	Name string `json:"name"`
	LastCommit Commit1 `json:"lastCommit"`
	// The URL of the page for creating a pull request from this branch. Max length is 2000 characters.
	CreatePullRequestUrl *string `json:"createPullRequestUrl,omitempty"`
	// The URL of the branch. Max length is 2000 characters.
	Url string `json:"url"`
}

type _Branch Branch

// NewBranch instantiates a new Branch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBranch(id string, updateSequenceId int64, name string, lastCommit Commit1, url string) *Branch {
	this := Branch{}
	this.Id = id
	this.UpdateSequenceId = updateSequenceId
	this.Name = name
	this.LastCommit = lastCommit
	this.Url = url
	return &this
}

// NewBranchWithDefaults instantiates a new Branch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBranchWithDefaults() *Branch {
	this := Branch{}
	return &this
}

// GetId returns the Id field value
func (o *Branch) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Branch) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Branch) SetId(v string) {
	o.Id = v
}

// GetIssueKeys returns the IssueKeys field value if set, zero value otherwise.
// Deprecated
func (o *Branch) GetIssueKeys() []string {
	if o == nil || IsNil(o.IssueKeys) {
		var ret []string
		return ret
	}
	return o.IssueKeys
}

// GetIssueKeysOk returns a tuple with the IssueKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Branch) GetIssueKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.IssueKeys) {
		return nil, false
	}
	return o.IssueKeys, true
}

// HasIssueKeys returns a boolean if a field has been set.
func (o *Branch) HasIssueKeys() bool {
	if o != nil && !IsNil(o.IssueKeys) {
		return true
	}

	return false
}

// SetIssueKeys gets a reference to the given []string and assigns it to the IssueKeys field.
// Deprecated
func (o *Branch) SetIssueKeys(v []string) {
	o.IssueKeys = v
}

// GetAssociations returns the Associations field value if set, zero value otherwise.
func (o *Branch) GetAssociations() []IssueIdOrKeysAssociation {
	if o == nil || IsNil(o.Associations) {
		var ret []IssueIdOrKeysAssociation
		return ret
	}
	return o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Branch) GetAssociationsOk() ([]IssueIdOrKeysAssociation, bool) {
	if o == nil || IsNil(o.Associations) {
		return nil, false
	}
	return o.Associations, true
}

// HasAssociations returns a boolean if a field has been set.
func (o *Branch) HasAssociations() bool {
	if o != nil && !IsNil(o.Associations) {
		return true
	}

	return false
}

// SetAssociations gets a reference to the given []IssueIdOrKeysAssociation and assigns it to the Associations field.
func (o *Branch) SetAssociations(v []IssueIdOrKeysAssociation) {
	o.Associations = v
}

// GetUpdateSequenceId returns the UpdateSequenceId field value
func (o *Branch) GetUpdateSequenceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdateSequenceId
}

// GetUpdateSequenceIdOk returns a tuple with the UpdateSequenceId field value
// and a boolean to check if the value has been set.
func (o *Branch) GetUpdateSequenceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateSequenceId, true
}

// SetUpdateSequenceId sets field value
func (o *Branch) SetUpdateSequenceId(v int64) {
	o.UpdateSequenceId = v
}

// GetName returns the Name field value
func (o *Branch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Branch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Branch) SetName(v string) {
	o.Name = v
}

// GetLastCommit returns the LastCommit field value
func (o *Branch) GetLastCommit() Commit1 {
	if o == nil {
		var ret Commit1
		return ret
	}

	return o.LastCommit
}

// GetLastCommitOk returns a tuple with the LastCommit field value
// and a boolean to check if the value has been set.
func (o *Branch) GetLastCommitOk() (*Commit1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastCommit, true
}

// SetLastCommit sets field value
func (o *Branch) SetLastCommit(v Commit1) {
	o.LastCommit = v
}

// GetCreatePullRequestUrl returns the CreatePullRequestUrl field value if set, zero value otherwise.
func (o *Branch) GetCreatePullRequestUrl() string {
	if o == nil || IsNil(o.CreatePullRequestUrl) {
		var ret string
		return ret
	}
	return *o.CreatePullRequestUrl
}

// GetCreatePullRequestUrlOk returns a tuple with the CreatePullRequestUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Branch) GetCreatePullRequestUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CreatePullRequestUrl) {
		return nil, false
	}
	return o.CreatePullRequestUrl, true
}

// HasCreatePullRequestUrl returns a boolean if a field has been set.
func (o *Branch) HasCreatePullRequestUrl() bool {
	if o != nil && !IsNil(o.CreatePullRequestUrl) {
		return true
	}

	return false
}

// SetCreatePullRequestUrl gets a reference to the given string and assigns it to the CreatePullRequestUrl field.
func (o *Branch) SetCreatePullRequestUrl(v string) {
	o.CreatePullRequestUrl = &v
}

// GetUrl returns the Url field value
func (o *Branch) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Branch) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Branch) SetUrl(v string) {
	o.Url = v
}

func (o Branch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Branch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.IssueKeys) {
		toSerialize["issueKeys"] = o.IssueKeys
	}
	if !IsNil(o.Associations) {
		toSerialize["associations"] = o.Associations
	}
	toSerialize["updateSequenceId"] = o.UpdateSequenceId
	toSerialize["name"] = o.Name
	toSerialize["lastCommit"] = o.LastCommit
	if !IsNil(o.CreatePullRequestUrl) {
		toSerialize["createPullRequestUrl"] = o.CreatePullRequestUrl
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *Branch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"updateSequenceId",
		"name",
		"lastCommit",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBranch := _Branch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBranch)

	if err != nil {
		return err
	}

	*o = Branch(varBranch)

	return err
}

type NullableBranch struct {
	value *Branch
	isSet bool
}

func (v NullableBranch) Get() *Branch {
	return v.value
}

func (v *NullableBranch) Set(val *Branch) {
	v.value = val
	v.isSet = true
}

func (v NullableBranch) IsSet() bool {
	return v.isSet
}

func (v *NullableBranch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBranch(val *Branch) *NullableBranch {
	return &NullableBranch{value: val, isSet: true}
}

func (v NullableBranch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBranch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


