/*
Jira Software Cloud API

Jira Software Cloud REST API documentation

API version: 1001.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger_software

import (
	"encoding/json"
)

// checks if the ChangelogHistoryMetadataAllOfGenerator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangelogHistoryMetadataAllOfGenerator{}

// ChangelogHistoryMetadataAllOfGenerator Details of the system that generated the history record.
type ChangelogHistoryMetadataAllOfGenerator struct {
	// The URL to an avatar for the user or system associated with a history record.
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	// The display name of the user or system associated with a history record.
	DisplayName *string `json:"displayName,omitempty"`
	// The key of the display name of the user or system associated with a history record.
	DisplayNameKey *string `json:"displayNameKey,omitempty"`
	// The ID of the user or system associated with a history record.
	Id *string `json:"id,omitempty"`
	// The type of the user or system associated with a history record.
	Type *string `json:"type,omitempty"`
	// The URL of the user or system associated with a history record.
	Url *string `json:"url,omitempty"`
}

// NewChangelogHistoryMetadataAllOfGenerator instantiates a new ChangelogHistoryMetadataAllOfGenerator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangelogHistoryMetadataAllOfGenerator() *ChangelogHistoryMetadataAllOfGenerator {
	this := ChangelogHistoryMetadataAllOfGenerator{}
	return &this
}

// NewChangelogHistoryMetadataAllOfGeneratorWithDefaults instantiates a new ChangelogHistoryMetadataAllOfGenerator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangelogHistoryMetadataAllOfGeneratorWithDefaults() *ChangelogHistoryMetadataAllOfGenerator {
	this := ChangelogHistoryMetadataAllOfGenerator{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDisplayNameKey returns the DisplayNameKey field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetDisplayNameKey() string {
	if o == nil || IsNil(o.DisplayNameKey) {
		var ret string
		return ret
	}
	return *o.DisplayNameKey
}

// GetDisplayNameKeyOk returns a tuple with the DisplayNameKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetDisplayNameKeyOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayNameKey) {
		return nil, false
	}
	return o.DisplayNameKey, true
}

// HasDisplayNameKey returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasDisplayNameKey() bool {
	if o != nil && !IsNil(o.DisplayNameKey) {
		return true
	}

	return false
}

// SetDisplayNameKey gets a reference to the given string and assigns it to the DisplayNameKey field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetDisplayNameKey(v string) {
	o.DisplayNameKey = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ChangelogHistoryMetadataAllOfGenerator) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ChangelogHistoryMetadataAllOfGenerator) SetUrl(v string) {
	o.Url = &v
}

func (o ChangelogHistoryMetadataAllOfGenerator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangelogHistoryMetadataAllOfGenerator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatarUrl"] = o.AvatarUrl
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.DisplayNameKey) {
		toSerialize["displayNameKey"] = o.DisplayNameKey
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableChangelogHistoryMetadataAllOfGenerator struct {
	value *ChangelogHistoryMetadataAllOfGenerator
	isSet bool
}

func (v NullableChangelogHistoryMetadataAllOfGenerator) Get() *ChangelogHistoryMetadataAllOfGenerator {
	return v.value
}

func (v *NullableChangelogHistoryMetadataAllOfGenerator) Set(val *ChangelogHistoryMetadataAllOfGenerator) {
	v.value = val
	v.isSet = true
}

func (v NullableChangelogHistoryMetadataAllOfGenerator) IsSet() bool {
	return v.isSet
}

func (v *NullableChangelogHistoryMetadataAllOfGenerator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangelogHistoryMetadataAllOfGenerator(val *ChangelogHistoryMetadataAllOfGenerator) *NullableChangelogHistoryMetadataAllOfGenerator {
	return &NullableChangelogHistoryMetadataAllOfGenerator{value: val, isSet: true}
}

func (v NullableChangelogHistoryMetadataAllOfGenerator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangelogHistoryMetadataAllOfGenerator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


