/*
Jira Software Cloud API

Jira Software Cloud REST API documentation

API version: 1001.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger_software

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeploymentData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentData{}

// DeploymentData Data related to a specific deployment in a specific environment that the deployment is present in. Must specify one of `issueKeys` or `associations`. 
type DeploymentData struct {
	// This is the identifier for the deployment. It must be unique for the specified pipeline and environment. It must be a monotonically increasing number, as this is used to sequence the deployments. 
	DeploymentSequenceNumber int64 `json:"deploymentSequenceNumber"`
	// A number used to apply an order to the updates to the deployment, as identified by the deploymentSequenceNumber, in the case of out-of-order receipt of update requests. It must be a monotonically increasing number. For example, epoch time could be one way to generate the updateSequenceNumber. 
	UpdateSequenceNumber int64 `json:"updateSequenceNumber"`
	// Deprecated. The Jira issue keys to associate the Deployment information with. Should replace this field with the \"associations\" field to associate Deployment information with issueKeys or other types of associations. 
	// Deprecated
	IssueKeys []string `json:"issueKeys,omitempty"`
	// The entities to associate the Deployment information with.
	Associations []DeploymentDataAssociationsInner `json:"associations,omitempty"`
	// The human-readable name for the deployment. Will be shown in the UI. 
	DisplayName string `json:"displayName"`
	// A URL users can use to link to this deployment, in this environment. 
	Url string `json:"url"`
	// A short description of the deployment 
	Description string `json:"description"`
	// The last-updated timestamp to present to the user as a summary of the state of the deployment. 
	LastUpdated time.Time `json:"lastUpdated"`
	// An (optional) additional label that may be displayed with deployment information. Can be used to display version information etc. for the deployment. 
	Label *string `json:"label,omitempty"`
	// The duration of the deployment (in seconds). 
	Duration *int64 `json:"duration,omitempty"`
	// The state of the deployment 
	State string `json:"state"`
	Pipeline Pipeline `json:"pipeline"`
	Environment Environment `json:"environment"`
	// A list of commands to be actioned for this Deployment 
	Commands []Command `json:"commands,omitempty"`
	// The DeploymentData schema version used for this deployment data.  Placeholder to support potential schema changes in the future. 
	SchemaVersion *string `json:"schemaVersion,omitempty"`
}

type _DeploymentData DeploymentData

// NewDeploymentData instantiates a new DeploymentData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentData(deploymentSequenceNumber int64, updateSequenceNumber int64, displayName string, url string, description string, lastUpdated time.Time, state string, pipeline Pipeline, environment Environment) *DeploymentData {
	this := DeploymentData{}
	this.DeploymentSequenceNumber = deploymentSequenceNumber
	this.UpdateSequenceNumber = updateSequenceNumber
	this.DisplayName = displayName
	this.Url = url
	this.Description = description
	this.LastUpdated = lastUpdated
	this.State = state
	this.Pipeline = pipeline
	this.Environment = environment
	var schemaVersion string = "1.0"
	this.SchemaVersion = &schemaVersion
	return &this
}

// NewDeploymentDataWithDefaults instantiates a new DeploymentData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentDataWithDefaults() *DeploymentData {
	this := DeploymentData{}
	var schemaVersion string = "1.0"
	this.SchemaVersion = &schemaVersion
	return &this
}

// GetDeploymentSequenceNumber returns the DeploymentSequenceNumber field value
func (o *DeploymentData) GetDeploymentSequenceNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DeploymentSequenceNumber
}

// GetDeploymentSequenceNumberOk returns a tuple with the DeploymentSequenceNumber field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetDeploymentSequenceNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentSequenceNumber, true
}

// SetDeploymentSequenceNumber sets field value
func (o *DeploymentData) SetDeploymentSequenceNumber(v int64) {
	o.DeploymentSequenceNumber = v
}

// GetUpdateSequenceNumber returns the UpdateSequenceNumber field value
func (o *DeploymentData) GetUpdateSequenceNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdateSequenceNumber
}

// GetUpdateSequenceNumberOk returns a tuple with the UpdateSequenceNumber field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetUpdateSequenceNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdateSequenceNumber, true
}

// SetUpdateSequenceNumber sets field value
func (o *DeploymentData) SetUpdateSequenceNumber(v int64) {
	o.UpdateSequenceNumber = v
}

// GetIssueKeys returns the IssueKeys field value if set, zero value otherwise.
// Deprecated
func (o *DeploymentData) GetIssueKeys() []string {
	if o == nil || IsNil(o.IssueKeys) {
		var ret []string
		return ret
	}
	return o.IssueKeys
}

// GetIssueKeysOk returns a tuple with the IssueKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *DeploymentData) GetIssueKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.IssueKeys) {
		return nil, false
	}
	return o.IssueKeys, true
}

// HasIssueKeys returns a boolean if a field has been set.
func (o *DeploymentData) HasIssueKeys() bool {
	if o != nil && !IsNil(o.IssueKeys) {
		return true
	}

	return false
}

// SetIssueKeys gets a reference to the given []string and assigns it to the IssueKeys field.
// Deprecated
func (o *DeploymentData) SetIssueKeys(v []string) {
	o.IssueKeys = v
}

// GetAssociations returns the Associations field value if set, zero value otherwise.
func (o *DeploymentData) GetAssociations() []DeploymentDataAssociationsInner {
	if o == nil || IsNil(o.Associations) {
		var ret []DeploymentDataAssociationsInner
		return ret
	}
	return o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetAssociationsOk() ([]DeploymentDataAssociationsInner, bool) {
	if o == nil || IsNil(o.Associations) {
		return nil, false
	}
	return o.Associations, true
}

// HasAssociations returns a boolean if a field has been set.
func (o *DeploymentData) HasAssociations() bool {
	if o != nil && !IsNil(o.Associations) {
		return true
	}

	return false
}

// SetAssociations gets a reference to the given []DeploymentDataAssociationsInner and assigns it to the Associations field.
func (o *DeploymentData) SetAssociations(v []DeploymentDataAssociationsInner) {
	o.Associations = v
}

// GetDisplayName returns the DisplayName field value
func (o *DeploymentData) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *DeploymentData) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetUrl returns the Url field value
func (o *DeploymentData) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DeploymentData) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value
func (o *DeploymentData) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DeploymentData) SetDescription(v string) {
	o.Description = v
}

// GetLastUpdated returns the LastUpdated field value
func (o *DeploymentData) GetLastUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdated, true
}

// SetLastUpdated sets field value
func (o *DeploymentData) SetLastUpdated(v time.Time) {
	o.LastUpdated = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *DeploymentData) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *DeploymentData) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *DeploymentData) SetLabel(v string) {
	o.Label = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *DeploymentData) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *DeploymentData) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *DeploymentData) SetDuration(v int64) {
	o.Duration = &v
}

// GetState returns the State field value
func (o *DeploymentData) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *DeploymentData) SetState(v string) {
	o.State = v
}

// GetPipeline returns the Pipeline field value
func (o *DeploymentData) GetPipeline() Pipeline {
	if o == nil {
		var ret Pipeline
		return ret
	}

	return o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetPipelineOk() (*Pipeline, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pipeline, true
}

// SetPipeline sets field value
func (o *DeploymentData) SetPipeline(v Pipeline) {
	o.Pipeline = v
}

// GetEnvironment returns the Environment field value
func (o *DeploymentData) GetEnvironment() Environment {
	if o == nil {
		var ret Environment
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetEnvironmentOk() (*Environment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *DeploymentData) SetEnvironment(v Environment) {
	o.Environment = v
}

// GetCommands returns the Commands field value if set, zero value otherwise.
func (o *DeploymentData) GetCommands() []Command {
	if o == nil || IsNil(o.Commands) {
		var ret []Command
		return ret
	}
	return o.Commands
}

// GetCommandsOk returns a tuple with the Commands field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetCommandsOk() ([]Command, bool) {
	if o == nil || IsNil(o.Commands) {
		return nil, false
	}
	return o.Commands, true
}

// HasCommands returns a boolean if a field has been set.
func (o *DeploymentData) HasCommands() bool {
	if o != nil && !IsNil(o.Commands) {
		return true
	}

	return false
}

// SetCommands gets a reference to the given []Command and assigns it to the Commands field.
func (o *DeploymentData) SetCommands(v []Command) {
	o.Commands = v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *DeploymentData) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentData) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *DeploymentData) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *DeploymentData) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

func (o DeploymentData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deploymentSequenceNumber"] = o.DeploymentSequenceNumber
	toSerialize["updateSequenceNumber"] = o.UpdateSequenceNumber
	if !IsNil(o.IssueKeys) {
		toSerialize["issueKeys"] = o.IssueKeys
	}
	if !IsNil(o.Associations) {
		toSerialize["associations"] = o.Associations
	}
	toSerialize["displayName"] = o.DisplayName
	toSerialize["url"] = o.Url
	toSerialize["description"] = o.Description
	toSerialize["lastUpdated"] = o.LastUpdated
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	toSerialize["state"] = o.State
	toSerialize["pipeline"] = o.Pipeline
	toSerialize["environment"] = o.Environment
	if !IsNil(o.Commands) {
		toSerialize["commands"] = o.Commands
	}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	return toSerialize, nil
}

func (o *DeploymentData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deploymentSequenceNumber",
		"updateSequenceNumber",
		"displayName",
		"url",
		"description",
		"lastUpdated",
		"state",
		"pipeline",
		"environment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentData := _DeploymentData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentData)

	if err != nil {
		return err
	}

	*o = DeploymentData(varDeploymentData)

	return err
}

type NullableDeploymentData struct {
	value *DeploymentData
	isSet bool
}

func (v NullableDeploymentData) Get() *DeploymentData {
	return v.value
}

func (v *NullableDeploymentData) Set(val *DeploymentData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentData(val *DeploymentData) *NullableDeploymentData {
	return &NullableDeploymentData{value: val, isSet: true}
}

func (v NullableDeploymentData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


